### ISSUE TITLE
Discovery is taking ages  and showing some errors in cloudwatch.

### ISSUE THREAD

**Issue by itsgsurya** [awslabs/aws-perspective#100]
**Describe the bug**
Discovery is taking ages

**Expected behavior**
 Discovery is taking ages and not showing any data. Errors in cloudwatch dashboards

**Screenshots**
![image](https://user-images.githubusercontent.com/25867181/101741103-f0ef8a80-3ac9-11eb-9fac-cd12924bdd06.png)

![image](https://user-images.githubusercontent.com/25867181/101742936-e41f6680-3aca-11eb-9dc5-a2ed47c7611a.png)

**Browser (please complete the following information):**

- Name [e.g. chrome]

**Additional context**

**Comment by svozza** [comment]
This is very likely related to the new Docker Hub rate limiting that causes the Discovery process container build process to fail. There is a full description and workaround here:

https://github.com/awslabs/aws-perspective/issues/98

**Comment by svozza** [comment]
Closing this as the discussion has moved to #98 .
