### ISSUE TITLE
Ability to filter resources by a specific TAG in any given resource tag list

### ISSUE THREAD

**Issue by caveman-bob** [awslabs/aws-perspective#102]
**Feature name**
Filter-on-tag-value

**Is your feature request related to a problem? Please describe.**
In my account I have thousands of resources, many with auto generated names.  I use cloud formation with different stacks serving different applications or purposes.   I would like to easily diagram each CF stack.  

**Describe the feature you'd like to see implemented**
Each of my CF stack's is created with a identification Tag which identifies its purpose.  This way all resources created by the stack will add this Tag.  For example  "MyCompanyProduct" = "Application-X".    I would like to be able to enter a value in a dialog box for whitelisting all resources which contain a particular Tag.   Once I do this, I should see only resources which pertain to my stack, and I can simply drag in all resources to build a diagram.

**Describe the value this feature will add to AWS Perspective**
This feature would bring a new level of value to anyone who wants to quickly build  diagram based tags they have given to their resources..

**Describe alternatives you've considered**
Alternate solution is to build the diagram by hand, or to create a new AWS account or role to isolate the resources, which is not practical in my enviornment.

**Additional context**
no additional contect.

**Comment by caveman-bob** [comment]
I didnt see the TAG filter when I wrote this, I am evaluating if it does what I would expect.

**Comment by svozza** [comment]
Did this do what you needed in the end?

**Comment by svozza** [comment]
I am going to close this issue for now, feel free to reopen if required.
