### ISSUE TITLE
Detection via API fails

### ISSUE THREAD

**Issue by AlexanderMannsfeld0007** [awslabs/aws-perspective#103]
**Describe the bug**
Resources from "Perspective-clients" are not collected, as soon they rely on "collection by API".

**To Reproduce**
Deployed a Master and client-setup.
The master itself detects the ECS cluster of itself, but the ECS-cluster of the clients not.
Additional set TLS and noPublicAccess for the Amplify-Bucket (tried it without => no change).

**Expected behavior**
Either AWS should collect ECS-resources via config or make the solution working.

**Additional context**

1. Common error when searching for 500/400 
(gremlin-CW-logs): {
    "detailedMessage": "Encountered a traverser that does not map to a value for child traversal: [GraphStep(vertex,[65e20b65ea59e1119673346af782dc4d])]",
    "code": "IllegalArgumentException",
    "requestId": "59b3a0a0-92a1-4707-85a2-bce6a9eba200"
}
2. ECS Log looks like:
![image](https://user-images.githubusercontent.com/65894736/102393205-5961ce80-3fd8-11eb-819e-75593d6f21ba.png)

3. NeptuneDB triggers CW-Alerts (we used the smallest instance, as around 4.5k resource are given in our test-setup):
![image](https://user-images.githubusercontent.com/65894736/102393384-96c65c00-3fd8-11eb-96a9-751f6667feb7.png)

IAM-Roles (Zoom...) are existing on the slaves, principal and the inline policies are looking good
AWS-config-bases resources are read fine (we are using our given AWS Config Setup)

4. AWS Codebuild has delivered an image (therefor no Docherhub issues here)

Rather clueless right now and looking for support / hep / hint / fix :-).

Thanks in advance &
Cheers,
Alexander

PS:
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html) => Done

**Comment by svozza** [comment]
Are you finding that the cluster is found but none of the services or tasks are? This is a known issue and is due to an error when parsing the v2 ARNs of ECS services. If so, we have a fix and it will be part of our 1.1.0 release in the new year.

**Comment by AlexanderMannsfeld0007** [comment]
Unfortunately only the ECS-Cluster of the Perspective-"Master" is found. 
From the members none of the resources only retrievable via API are collected.

**Comment by svozza** [comment]
Yes, then it's the bug I've described above, the error means that the whole ECS discovery process fails and Perspective moves to the next resource type. As I said, we are aware of this and it will be fixed in the next release.

**Comment by AlexanderMannsfeld0007** [comment]
Perfect, then I'm absolutely relieved :-). Do you have an estimate, when 1.10 will be released? 
Is the Perspective-"Master" then als deployable via Stacksets?

**Comment by svozza** [comment]
We are aiming for the middle of January (obviously this is subject to change) to release version 1.1.0. I'm not sure what you mean by deploying the master with Stacksets. Do you want to install Perspective in different regions?

**Comment by AlexanderMannsfeld0007** [comment]
No, I was looking forward to deploy Perspective-Masters on selected accounts via a stackset-instance from our masterpayer.
We are responsible for recently 284 AWS-accounts, distributed via several teams. 
After some tests we come to the conclusion, that one Perspective-"Master" is due it's limitations not suited for our case, but a team-wise-approach (eg one Perspective-"Master" per team) would be.
but: deploying individually in 40 teams without using stacksets is not something we are looking for, especially due limitations regarind further update-processes (via stacksets it's just so convenient).
![image](https://user-images.githubusercontent.com/65894736/102398819-0e4bb980-3fe0-11eb-8e5d-bea81a8a7712.png)

**Comment by svozza** [comment]
Hey Alexander, apologies that this got lost over the holiday period. I've looked into the issue and the workarounds proposed (https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/207) won't work for us given how the Perspective CloudFormation is structured. I'm not sure what we can do given the current limitations of Stacksets to get around this.

**Comment by svozza** [comment]
@AlexanderMannsfeld0007 so it looks like Serverless tranforms are now supported!

https://aws.amazon.com/about-aws/whats-new/2021/04/you-can-now-use-macros-and-transforms-in-cloudformation-templates-to-create-aws-cloudformation-stacksets/

**Comment by thebutler12** [comment]
Please create a new issue tagged with v1.1.0 if you are still experiencing this issue.
