### ISSUE TITLE
import configuration

### ISSUE THREAD

**Issue by BuffaloBorn** [awslabs/aws-perspective#104]
After logging with a new user, I received the following error message: 

`We could not retrieve your import configuration or it has been corrupted. See GitHub issues for help resolving the issue`

**Comment by svozza** [comment]
Is this a fresh install or have you imported some accounts?

**Comment by svozza** [comment]
I am going to close this issue as we've not heard back in a while but please feel free to reopen if you want to continue debugging this issue.
