### ISSUE TITLE
Resource loading is not completing

### ISSUE THREAD

**Issue by madhubysani01** [awslabs/aws-perspective#106]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
Configured AWS Perspective  stack.  After logging into the Cloudfront URL, choosen account and region  details. Resource loading is not getting  completed after. 5 Hours too.  Need guidance. 

**To Reproduce**

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]. Chrome
- Version [e.g. 22] : Version 87.0.4280.88 (Official Build) (x86_64)

**Additional context**

**Comment by svozza** [comment]
It's very likely this issue: https://github.com/awslabs/aws-perspective/issues/98. There's a workaround in the linked issue too.

**Comment by svozza** [comment]
I'm going to close this issue for now, if it wasn't #98 then please feel free to reopen.
