### ISSUE TITLE
Email with user/password should include link to the CF url

### ISSUE THREAD

**Issue by spohle** [awslabs/aws-perspective#116]
**Feature name**
Welcome Email with more information and only after the whole nested stack has been deployed

**Is your feature request related to a problem? Please describe.**
A description of what the problem is.

**Describe the feature you'd like to see implemented**
The welcome email which currently holds the admin user and password should include more info like the Cloudfront url and should only be sent once all the stacks have been deployed.

**Describe the value this feature will add to AWS Perspective**
User won't have to find the CF url in the cloudformation stacks

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by thebutler12** [comment]
Closing as it could raise security issues sending all this data in a single email.
