### ISSUE TITLE
Not able to launch stack properly

### ISSUE THREAD

**Issue by wharpreet** [awslabs/aws-perspective#119]
I Followed the guide but still not able to launch the stack properly.
I am facing multiple issues:
* Cloud formation fails to launch full-stack. In this case, I tried launching individual nested stacks and am able to launch them without any issue (by copying template files one by one). But in the end, nothing is getting discovered (screenshot attached).
* In one case (different account) it got launched without error, was able to discover resources, but the "All" tab had no dropdown, hence no graph was generated. 
* Tried to delete and re-create the stack from the second/above case, then this also gave issue same as the first point. 

---
**Describe the bug**
Due to less logging, not able to figure out the exact reason for failure.

**To Reproduce**
1. Just try to set up the stack.

**Expected behavior**
The expectation is to have a fully deployed and functional AWS Perspective stack.

**Screenshots**
Attached screen where nothing is getting discovered after I manually launched individual nested stacks
<img width="1666" alt="Screen Shot 2021-02-16 at 6 35 50 PM" src="https://user-images.githubusercontent.com/1982952/108148639-167ab080-7086-11eb-87f5-01b568619577.png">

**Browser (please complete the following information):**
Tried both Chrome (Version 88.0.4324.150) and Firefox (84.0.1)

**Comment by thebutler12** [comment]
Can you provide some detail about the error you were seeing when you tried to deploy the full stack please?

**Comment by wharpreet** [comment]
<img width="1202" alt="Screen Shot 2021-02-17 at 1 32 13 PM" src="https://user-images.githubusercontent.com/1982952/108270774-bedf5200-7124-11eb-8c06-12bd7f736b27.png">

It fails for few nested stacks and then bails out.
In one scenario, I noticed that even though it said "CREATE_FAILED" for one section, but the actual nested stack said "CREATE_COMPLETE"

**Comment by wharpreet** [comment]
Please note, when I tried launching the failed stacks from the above screenshot, they got created successfully.

**Comment by svozza** [comment]
What are the errors in the `DiscoveryImport` stack, you should be able to see them if you if you look at the deleted stacks in the cfn console. This looks like there was some issue setting up AWS Config.

<img width="426" alt="Screenshot 2021-02-17 at 23 09 36" src="https://user-images.githubusercontent.com/8573472/108280065-83b93f00-7175-11eb-8b7f-1151277331db.png">

**Comment by wharpreet** [comment]
It has these errors:
The following resource(s) failed to create: [ConfigBucketBucketPolicy, DeliveryChannel, ConfigRole]. 

Failed to put delivery channel 'aws-perspective-XXXXXXXX-us-east-1-DiscoveryImport-1C0RNY70EJYKH-DeliveryChannel-QZ4PE83OHFA5' because the maximum number of delivery channels: 1 is reached. (Service: AmazonConfig; Status Code: 400; Error Code: MaxNumberOfDeliveryChannelsExceededException; Request ID: 4edc54bc-8c85-4925-b99d-7ef9c73215b3; Proxy: null)

**Comment by svozza** [comment]
That means Config has already been set up in the region, you'll need to run the template with the `AlreadyHaveConfigSetup` paramter set to `Yes`.

**Comment by wharpreet** [comment]
Let me try and get back

**Comment by wharpreet** [comment]
Any idea how much time does it take to load the resources in UI?
After the above change (AlreadyHaveConfigSetup) it deployed everything successfully, but nothing showed up in UI for the last 20 mins.

**Comment by svozza** [comment]
You could be encountering the new download limits that DockerHub introduced a few months ago, more info and workaround here: https://github.com/awslabs/aws-perspective/issues/98

**Comment by wharpreet** [comment]
Thanks guys for help. Resources popped up after sometime.

**Comment by svozza** [comment]
Happy to help!

**Comment by wharpreet** [comment]
Any idea if this can be used along with Flow logs to give a better-connected diagram?
I tried selecting individual resources, but it doesn't show the connection between them, for example EC2 instance and RDS.

**Comment by svozza** [comment]
Not yet but this has come up before with other customers and it's something that's on our backlog.
