### ISSUE TITLE
Receiving 'account must be verified' on nested CF stack

### ISSUE THREAD

**Issue by troydieter** [awslabs/aws-perspective#12]
**Describe the bug**
On deployment using the CloudFormation stack, it is halted on a nested-stack with the following:

`Your account must be verified before you can add new CloudFront resources. To verify your account, please contact AWS Support (https://console.aws.amazon.com/support/home#/ ) and include this error message. (Service: AmazonCloudFront; Status Code: 403; Error Code: AccessDenied; Request ID: XXX-XXX)`

**To Reproduce**

1. Deploy the CloudFormation stack for aws-perspective per the deployment guide
2. The behavior is experienced on the nested stack creation for CloudFront

**Expected behavior**
Creation of the CloudFront distributions as expected.

**Additional context**
If additional service quotas or preliminary steps are required, specify it as such in the documentation. [Perhaps under the design considerations](https://docs.aws.amazon.com/solutions/latest/aws-perspective/design-considerations.html)?

**Comment by thebutler12** [comment]
Hi, thanks for raising this. Did you manage to get help from AWS Support to verify your account?

**Comment by troydieter** [comment]
> Hi, thanks for raising this. Did you manage to get help from AWS Support to verify your account?

Hi Matt, I've raised support case 7409691961 to help resolve this.

**Comment by khan-asif** [comment]
Deployment was successful, didn't see this issue.

**Comment by troydieter** [comment]
Closing as this is account-specific and does not pertain to overall deployment.
