### ISSUE TITLE
"We could not retrieve your import configuration or it has been corrupted. See GitHub issuesfor help resolving the issue"

### ISSUE THREAD

**Issue by gherlein** [awslabs/aws-perspective#120]
**Describe the bug**
on initial launch, get the error: "We could not retrieve your import configuration or it has been corrupted. See GitHub issuesfor help resolving the issue"

**To Reproduce**
Deploy https://github.com/gherlein/lamp-aws-cloudformation then launch perspective

**Expected behavior**
Should have seen something in the GUI instead of the error

**Screenshots**
![image](https://user-images.githubusercontent.com/173428/108432656-937a6700-71f9-11eb-97e1-e2cbf6a1bc11.png)

**Browser (please complete the following information):**
Chrome Version 88.0.4324.150 (Official Build) (x86_64)

**Comment by svozza** [comment]
How many resources have you imported? This can happen when there are so many resources that the payload limit for lambda has been breached as you can see here: https://github.com/awslabs/aws-perspective/issues/27.

**Comment by gherlein** [comment]
Wow, it's not that big...
[Design.pdf](https://github.com/awslabs/aws-perspective/files/6006619/Design.pdf)

Basic HA two AZ, dual VPC lamp stack with RDS backing - sitting behind ELB.  This is a really small footprint.

**Comment by gherlein** [comment]
I saw that the DiscoveryImport stack failed to create - that must be related.  I will totally rebuild and see if I can reproduce.

**Comment by svozza** [comment]
yeah, it's defintely not that, if the Discovery import stack failed, it might be that AWS config was already installed. Someone had a similar issue like that yesterday: https://github.com/awslabs/aws-perspective/issues/119.

**Comment by gherlein** [comment]
That was it.  We should update the docs at https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html to instruct the user that ALL the nested CF templates must succeed, and to warn them to change the setting if they have AWS Config already set up.  But we can close this issue.
