### ISSUE TITLE
Stack Creation Time Exceeded the Specified Timeout for "ElasticsearchStack"

### ISSUE THREAD

**Issue by stetsonw** [awslabs/aws-perspective#123]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
Every stack completes except for the "ElasticsearchStack."

**To Reproduce**
Simply deploying AWS Perspective reproduces this problem.

**Expected behavior**
Stack creation should complete

**Screenshots**

![image](https://user-images.githubusercontent.com/79669025/109224146-89bcaa80-7789-11eb-8e34-6d2c4e218c24.png)

![image](https://user-images.githubusercontent.com/79669025/109224191-9e993e00-7789-11eb-8d4d-a63682494191.png)

**Browser (please complete the following information):**

- Name: Firefox
- Version: 78.8.0esr

**Additional context**
None

**Comment by thebutler12** [comment]
Please create a new issue tagged with v1.1.0 if you are still experiencing this issue.
