### ISSUE TITLE
Upgrade procedure

### ISSUE THREAD

**Issue by rsiripan** [awslabs/aws-perspective#138]
Hi,

We have deployed version 1.0.0 from the CF template and would like to upgrade to version 1.0.1.
Could you please guide me to a procedure how-to upgrade please.

Thanks

**Comment by svozza** [comment]
Hi there, unfortunately the upgrade from 1.0.0 to 1.0.1 requires uninstalling and reinstalling the soultion, however, in the new version, which we will hopefully be releasing in next month or so (this date may slip though) will allow you to upgrade by just using the CloudFormation update functionality.
