### ISSUE TITLE
Consildated cost with large CUR report

### ISSUE THREAD

**Issue by trtruong** [awslabs/aws-perspective#141]
I have a large consolidated CUR report with 1.5Gb zipped and 22.5Gb unzipped.  the lambda function seems not able to handle.  i've tried to increase memory from 3008 -> 4096 and increase runtime to max 15 mins still didn't help

---

**Describe the bug**
lambda log
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**To Reproduce**

1. dropped a CUR .zip file into the S3 bucket

**Expected behavior**
Cost data showing in Perspective

**Comment by svozza** [comment]
Hi there, the cost feature has been rewritten from scratch for v1.1.0 so this issue will no longer be a problem. We are hoping to have the new version out in the next 4-5 weeks although this is not a firm date.

**Comment by svozza** [comment]
I'm going to close this issue but I will reply when our release is out to let you know it's ready.
