### ISSUE TITLE
Deployed successfully but unable to import accounts

### ISSUE THREAD

**Issue by quasitime** [awslabs/aws-perspective#145]
**Describe the bug**
This is a fresh cloudformation deployment of the solution, using the link here:
https://aws.amazon.com/solutions/implementations/aws-perspective/

I am able to log into the Perspective GUI with Admin, but unable to import accounts.  Upon going through the menu to import an account (the current account we deployed perspective to), I get an error saying "We could not complete that action. Please try again. See GitHub issues for help resolving the issue.

**To Reproduce**

1. Login to Perspetive GUI
2. Go to Configuration -> Accounts & Regions
3. Select Import -> Import an account
4. Enter account number (current account)

**Expected behavior**
Expect to see a success message that resources in the current account will be discovered.

**Screenshots**
<img width="995" alt="Screen Shot 2021-04-16 at 2 34 26 PM" src="https://user-images.githubusercontent.com/41212365/115087265-b1470e00-9ec2-11eb-938f-eba2beca5f90.png">

**Browser (please complete the following information):**

- Firefox
- Version 87.0

**Additional context**

**Comment by quasitime** [comment]
So I think this might be related to SCPs or post deploy permissions.  I had to disable a Config-related SCP to get the deploy to run successfully.

**Comment by svozza** [comment]
Ah I see, are you using Landing Zone? I know by default it denies the `Config:PutConfigurationAggregator` API call, which is required for Perspective to be able to add accounts to scan.

**Comment by quasitime** [comment]
Thank you @svozza I'll look into that.  Your suspicion was also correct on the Config API call being blocked.  👍 

Going to close this out.  The issue was definitely a Config related SCP that was blocking the Config:PutConfigurationAggregator API call.

**Comment by svozza** [comment]
Ah glad we figured it out. I think it would make sense for use to add some documentation around this issue because it's come up before so I'll add a task for that to our backlog.
