### ISSUE TITLE
When we deploy the solution, I was able to navigate "ALL" and "TYPES" under resources section. After 5 to 6 hrs, I'm not able to navigate any of them. 

### ISSUE THREAD

**Issue by mrlsdevops** [awslabs/aws-perspective#147]
![image](https://user-images.githubusercontent.com/39660674/116204829-20b2ce00-a70b-11eb-85cc-6b249919e581.png)

After 5 to 6 hrs 

I no longer see explore any of resources under 'ALL' and 'TYPES'

![image](https://user-images.githubusercontent.com/39660674/116205094-65d70000-a70b-11eb-8a16-83f601d85752.png)

Please advise

**Comment by svozza** [comment]
Are there any errors in the browser console?

**Comment by mrlsdevops** [comment]
No Errors in the console. It's saying discovery is in the progress even when I stop container tasks.

**Comment by svozza** [comment]
What does it say in the network tab when you refresh the page? Are there any 4xx or 5xx errors?

**Comment by mrlsdevops** [comment]
No 400 or 500 errors. All it’s saying discovery is in progress.

**Comment by svozza** [comment]
Apologies for the late response here, just a quick question, how many accounts are you currently importing?

**Comment by mrlsdevops** [comment]
I am planning to import 10 accounts

**Comment by svozza** [comment]
Have you imported them all via the UI yet?

**Comment by mrlsdevops** [comment]
Sorry I got confused. This error went away after redeploy Solution.

I am good here.

**Comment by svozza** [comment]
Ah good! Although, I would say that if I were you I would add accounts maybe 2-3 at a time allow the discover process to run and then when that's done, add another 2-3 etc. The version of Perspective you're using tries to make API calls for all the accounts all at once, which ends up getting rate limited by the AWS Config API. The new version has client side throttling that tries to minimise these errors.

**Comment by mrlsdevops** [comment]
Where can I find new version? I wish I could deploy new version if it’s
available.

Please advise

**Comment by svozza** [comment]
It's not out yet, you will be able to upgrade by just using the CloudFormation `Update` functionality. I will reply to this thread when we have released.

**Comment by mrlsdevops** [comment]
Awesome, looking forward for new version.

thanks!

**Comment by mrlsdevops** [comment]
Is there any ETA on this?

**Comment by svozza** [comment]
I can't commit to dates but we're aiming for a few weeks time.

**Comment by mrlsdevops** [comment]
Sounds good.

**Comment by svozza** [comment]
No problem! I'm going to close this issue now but I can still reply to it to give it a bump when the new version is released.
