### ISSUE TITLE
Hide certain Resource Types on an existing diagram

### ISSUE THREAD

**Issue by khan-asif** [awslabs/aws-perspective#16]
**Feature name**
Hide Resource Types

**Is your feature request related to a problem? Please describe.**
Yes. Avoid clutter on a diagram by turning off non-essential resource types when the diagram is generated by selection of application resource tags.

**Describe the feature you'd like to see implemented**
An option on right click on diagram to hide certain resource types or grey out the icon and connection links.

**Describe the value this feature will add to AWS Perspective**
Allows better focus on essential services.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mohsanjaffery** [comment]
Certain kinds of resources can be hidden from view by using the **Filters** option found under **Preferences** in the left pane - see  [here](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-a-web-ui-features-and-common-tasks.html#filtering-in-aws-perspective) for more details.

You can also filter out a group of resources  (e.g. tags) in an existing diagram by right clicking on the relevant bounding box and selecting the **Removal All** option from the context menu.  Would this satisfy your use case?

**Comment by khan-asif** [comment]
> Certain kinds of resources can be hidden from view by using the **Filters** option found under **Preferences** in the left pane - see [here](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-a-web-ui-features-and-common-tasks.html#filtering-in-aws-perspective) for more details.
> 
> You can also filter out a group of resources (e.g. tags) in an existing diagram by right clicking on the relevant bounding box and selecting the **Removal All** option from the context menu. Would this satisfy your use case?

Thanks @mohsanjaffery that worked, but that revealed another limitation. Let me open separate request for that.

**Comment by mohsanjaffery** [comment]
Okay @khan-asif, glad that worked for you.  I'll close this issue and we'll keep an eye for the other request.
