### ISSUE TITLE
Not able to download diagram that way we customize 

### ISSUE THREAD

**Issue by mrlsdevops** [awslabs/aws-perspective#163]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---
We are unable to download PNG the way we organize resources in the diagram. All we getting is zigzag manner when we download PNG and not able to download the way we organize  

**Describe the bug**
A description of what the bug is.

**To Reproduce**

**Expected behavior**
we need diagram the way we organize when we download PNG 

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by thebutler12** [comment]
Thanks for raising this. Are you able to send us an example of what PNG it is producing?

**Comment by svozza** [comment]
Hi there, this issue has been inactive for quite some time. I'm going to close it but please feel free to reopen if you would like to continue debugging.
