### ISSUE TITLE
We are not able to See Compenents in the AWS perspective 

### ISSUE THREAD

**Issue by jityadav** [awslabs/aws-perspective#177]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
A description of what the bug is.

**To Reproduce**

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by jityadav** [comment]
<img width="945" alt="AWS Perpesctive" src="https://user-images.githubusercontent.com/44487715/124904718-eadf6f00-e002-11eb-927e-0fa5dc27eed6.PNG">

Here we can not see the list and components in the aws perspective , it is used to work before but now not working
<img width="945" alt="AWS Perpesctive" src="https://user-images.githubusercontent.com/44487715/124904869-119da580-e003-11eb-97ce-e0aece111f8b.PNG">

**Comment by svozza** [comment]
If you open Dev Tools there any errors in the browser console?

**Comment by jityadav** [comment]
yes there are some errors, we can see here

<img width="952" alt="error" src="https://user-images.githubusercontent.com/44487715/124906038-4827f000-e004-11eb-8ac0-cbf7e77badad.PNG">

**Comment by svozza** [comment]
This turned out to be an out of memory exception in the Gremlin lambda. Increasing the memory of the lambda solved the problem.

**Comment by jityadav** [comment]
> This turned out to be an out of memory exception in the Gremlin lambda. Increasing the memory of the lambda solved the problem.

Thanks for quick resolution...

**Comment by svozza** [comment]
No problem! 😄
