### ISSUE TITLE
no option to see "Types" or "All"

### ISSUE THREAD

**Issue by jacekfeldman** [awslabs/aws-perspective#181]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
Not possible to draw anything. Looks like tool discovered resources but there is no option to see "Types" or "All". 

<img width="623" alt="image" src="https://user-images.githubusercontent.com/75030628/126889908-046abc31-0e79-44a0-b0a0-6bf248d2cac7.png">

**To Reproduce**

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by svozza** [comment]
I think this may be an error in the Gremlin lambda function. Can you disable the the scheduled ECS task by running the following command in the cli:

```bash
aws events disable-rule --name aws-perspective-<account-number>-rule
```

And make sure that the Discovery task is not running (it uses the same API as the frontend and it makes it very difficult to find any errors if it's running).

Then refresh the the Perspective frontend and go to the logs for the `GremlinFunction` lambda function and see what errors you see.

To re-eanble the scheduled tak, just do this command:

```bash
aws events enable-rule --name aws-perspective-<account-number>-rule
```

**Comment by thebutler12** [comment]
Please upgrade to v1.1.10 and create a new issue tagged with v1.1.0 if you are still experiencing this issue.
