### ISSUE TITLE
Help on the ERROR "We could not retrieve your import configuration or it has been corrupted. "

### ISSUE THREAD

**Issue by siluo** [awslabs/aws-perspective#182]
After i updated the password by clicking the URL displayed on the CloudFrontDistribution stack, i received the error "We could not retrieve your import configuration or it has been corrupted. " Not sure if there is anything missing here. Thanks

**Comment by svozza** [comment]
What does it say in the the network tab of dev tools? Are there any errors in the browser console?

**Comment by siluo** [comment]
@svozza here is the screenshot:
<img width="918" alt="Screen Shot 2021-07-28 at 11 39 35 AM" src="https://user-images.githubusercontent.com/11355900/127378042-2174c3aa-adc2-4130-a5bc-6cae172acb05.png">

**Comment by svozza** [comment]
Hmm, something weird going on with the graphql endpoint. Can you go to the logs for the `SettingsFunction` lambda function and see if there are any errors in there?

**Comment by siluo** [comment]
@svozza May I know where can i locate the logs for the SettingsFunction lambda function? is it still under CloudFormation?

**Comment by svozza** [comment]
If you find that function in the Lambda console (just type 'Settings' into the search bar and it will appear) you'll be able to reach the logs from the Monitoring tab.

**Comment by siluo** [comment]
@svozza i did that before and i did not find it. Here is all what i have:
<img width="1424" alt="Screen Shot 2021-07-28 at 1 12 50 PM" src="https://user-images.githubusercontent.com/11355900/127389346-7c55cbc2-ce90-4355-94a5-c641e3d1829f.png">

**Comment by svozza** [comment]
It looks like there was a problem with the install, you're missing most of the lambdas. Can you check in the CloudFormation console and see if there are errors there?  There should be around 20 stacks related to Perspective.

**Comment by siluo** [comment]
@svozza Thanks. You are right. In total i have 25 stacks and 14 of them are perspective related. Among these 14, there are 2 stacks marked with CREATE_FAILED status: aws-perspective-833543886316-us-east-1-DiscoveryImport-109SHKA1S32L8(NESTED) and aws-perspective-833543886316-us-east-1
Is the nested one causing the failure of the main template one?

<img width="1402" alt="Screen Shot 2021-07-29 at 8 57 24 AM" src="https://user-images.githubusercontent.com/11355900/127525721-d7d2e485-e0af-4569-b5d4-f7a90c3bcc95.png">

**Comment by svozza** [comment]
My guess is that you already have Config enabled in this region and the error is that it is trying to create a delivery channel that already exists. If you click into the Config Aggregator stack you'll see the error in there. If that is the problem, then the solution is to delete the current stack and reinstall but to set the `AlreadyHaveConfigSetup` parameter to `Yes`.

**Comment by svozza** [comment]
Oops, accidentally closed the issue.

**Comment by siluo** [comment]
@svozza when you say "delete the current stack", are you referring to delete the stack of "aws-perspective-833543886316-us-east-1" ? and reinstall everything with setting the AlreadyHaveConfigSetup parameter to Yes. https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html#step-1.-launch-the-stack? 

Do i need to delete the stack "digital-architecture-diagrams-from-perspective" before reinstall? Thanks

**Comment by svozza** [comment]
Follow the steps here to completely uninstall the solution: https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-f-uninstall-the-solution.html. Then reinstall with that option changed.

**Comment by siluo** [comment]
@svozza  Yes, after delete both stacks and reinstall with setting the AlreadyHaveConfigSetup parameter to Yes, the page is loading now. Thank you so much for the help~

**Comment by svozza** [comment]
No problem, glad we got it sorted!
