### ISSUE TITLE
Lambda not appearing under 'Resources' in Perspective 

### ISSUE THREAD

**Issue by siluo** [awslabs/aws-perspective#184]
**Describe the bug**
I deployed the stack to import an account using the AWS Perspectivem, everything deployed ok(see screenshot 1). The total number of resources shows 3935, but under All there is no Lambda(see screenshot 2). I checked the AWS config both "Record all resources supported in this region" and "Include global resources (e.g., AWS IAM resources)" were selected.

**To Reproduce**
 Import an account into AWS perspective

**Expected behavior**
Excepted the Lambda functions to appear in Perspective.

**Screenshots**
<img width="1515" alt="Screen Shot 2021-08-03 at 11 07 43 AM" src="https://user-images.githubusercontent.com/11355900/128064767-26584a39-d45c-488d-ad9f-5d0e6654e675.png">

![Screen Shot 2021-08-03 at 11 05 47 AM](https://user-images.githubusercontent.com/11355900/128064492-8b589eb3-1542-40b8-ba76-8872e023f263.png)

**Comment by thebutler12** [comment]
Hi,

That's a strange one. Can you confirm you have made the Region discoverable that contains the Lambda functions? 

Can you also please follow the steps [here](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html) to check whether the discovery component is having trouble gathering data for Lambda functions?

**Comment by siluo** [comment]
Thanks for your reply @thebutler12 .

Could you please provide more details about how to  ensure the Region discoverable? Like I mentioned in the post "I checked the AWS config both "Record all resources supported in this region" and "Include global resources (e.g., AWS IAM resources)" were selected." for the account which was imported:
<img width="1171" alt="Screen Shot 2021-08-04 at 3 16 06 PM" src="https://user-images.githubusercontent.com/11355900/128262407-5f071b7c-4970-4767-9749-90f375f3545f.png">

And when i checked the discovery component, I was unable to find the GremlinFunction under the Lambda functions for the account which was imported:
<img width="1266" alt="Screen Shot 2021-08-04 at 3 22 02 PM" src="https://user-images.githubusercontent.com/11355900/128262979-01d8a442-3714-4a56-a5bb-d57559bd7d1d.png">

**Comment by thebutler12** [comment]
Hi,

Did you follow the steps for **Importing an account** and/or **Importing a Region** in the [deployment guide](https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html#step-2.-post-deployment-configuration-tasks) for the AWS Account and Region that contains the Lambda functions? 

For the discovery component debugging. Are you sure you are in the AWS Account and Region you deployed Perspective in? If the Gremlin Lambda function didn't exist your UI would be failing. 

Cheers,

Matt

**Comment by siluo** [comment]
@thebutler12 Yes, I followed the  **Importing an account** in the deployment guide for the AWS Account and Region that contains the Lambda functions. And I was in the deployed account with Perspective in. I was able to see this account shown in the AWS Perspective without any error
![Screen Shot 2021-08-05 at 8 09 20 AM](https://user-images.githubusercontent.com/11355900/128374243-eab4b5ee-c6f3-470a-845b-dcf08110944d.png)

**Comment by siluo** [comment]
Hey Matt,

I am going to remove this account and redo the deployment again to see if it is able to fix the issue. @thebutler12 

Thanks
Sisi

**Comment by siluo** [comment]
@thebutler12 unfortunately, even i redid everything i still could not see the Lambda displayed under the Resources section in AWS perspective.

**Comment by thebutler12** [comment]
Sorry to hear you are still having issues. 

The debugging steps are to be performed in the account/Region you deployed AWS Perspective. Please follow the steps again within that account/Region and report any errors that you find in the logs.

**Comment by siluo** [comment]
@thebutler12 Sorry I was on vacation for the past few days. I have been doing the debug in the account/Region I deployed AWS Perspective. Not sure if it is Ok to meet with you online so I can show you how it looks like.

**Comment by siluo** [comment]
@thebutler12 I may find something you need. So just to explain the case clearly: I have an account **A** we created just for AWS perspective based on the[ recommendation](https://docs.aws.amazon.com/solutions/latest/aws-perspective/design-considerations.html). So this account is a brand new AWS account. I launched the AWS CloudFormation template into this account. Then I imported account **B** which has all the resources/workloads we would like to generate the diagram from.

So now I was able to see the account **B** lambda functions listed when logging into the AWS Perspective link provided by account **A** but there was no GremlinFunction listed under account **B** lambda functions. 

However, I could locate GremlinFunction within account **A** lambda functions. And I searched 400/500 in the latest Log streams under CloudWatch monitor which was able to return several entries. 

Here is the returned entires from the latest log stream for 400 error:
![Screen Shot 2021-08-19 at 12 09 37 AM](https://user-images.githubusercontent.com/11355900/130024093-8da3adb2-9750-4c13-96df-db1862d38219.png)

And here is the returned entires from the latest log stream for 500 error:
![Screen Shot 2021-08-19 at 12 08 18 AM](https://user-images.githubusercontent.com/11355900/130024008-25d277f9-263c-4403-8076-5f3217eaaa2b.png)

It looks like this maybe the error that causing the account **B** is unable to display the GremlinFunction? Could you please help us confirm it?
`2021-08-18T23:48:45.842-07:00

Copy
2021-08-19T06:48:45.842Z	8637c6c2-ab4e-4c69-aeb1-6cb4000b48c1	INFO	ResponseError: Server error: 
{
    "code": "ConstraintViolationException",
    "requestId": "0a0fe863-aa17-44bf-aa01-1f6c7db4a780",
    "detailedMessage": "Vertex with id already exists: "
}
 (499)
    at Connection._handleMessage (/var/task/node_modules/gremlin/lib/driver/connection.js:282:9)
    at WebSocket.<anonymous> (/var/task/node_modules/gremlin/lib/driver/connection.js:130:43)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.EventEmitter.emit (domain.js:483:12)
    at Receiver.receiverOnMessage (/var/task/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.EventEmitter.emit (domain.js:483:12)
    at Receiver.dataMessage (/var/task/node_modules/ws/lib/receiver.js:413:14)
    at /var/task/node_modules/ws/lib/receiver.js:379:23
    at /var/task/node_modules/ws/lib/permessage-deflate.js:298:9 {
  statusCode: 499,
  statusMessage: '{"code":"ConstraintViolationException","requestId":"0a0fe863-aa17-44bf-aa01-1f6c7db4a780","detailedMessage":"Vertex with id already exists: "}',
  statusAttributes: {}
}`

**Comment by siluo** [comment]
Create a new issue since now we miss the GremlinFunction not the whole Lambda https://github.com/awslabs/aws-perspective/issues/193
