### ISSUE TITLE
GremlinFunction not appearing in Lambda of Perspective possible due to "Vertex with id already exists: "

### ISSUE THREAD

**Issue by siluo** [awslabs/aws-perspective#193]
**Describe the bug**
I have an account **A** we created just for AWS perspective based on the[ recommendation](https://docs.aws.amazon.com/solutions/latest/aws-perspective/design-considerations.html). So this account is a brand new AWS account. I launched the AWS CloudFormation template into this account. Then I imported account **B** which has all the resources/workloads we would like to generate the diagram from.

So now I was able to see the account **B** lambda functions listed when logging into the AWS Perspective link provided by account **A** but there was no GremlinFunction listed under account **B** lambda functions. 

However, I could locate GremlinFunction within account **A** lambda functions. And I searched 400/500 in the latest Log streams under CloudWatch monitor which was able to return several entries. 

It looks like this maybe the error that causing the account **B** is unable to display the GremlinFunction? Could you please help us confirm it?

```
2021-08-18T23:48:45.842-07:00

Copy
2021-08-19T06:48:45.842Z	8637c6c2-ab4e-4c69-aeb1-6cb4000b48c1	INFO	ResponseError: Server error: 
{
    "code": "ConstraintViolationException",
    "requestId": "0a0fe863-aa17-44bf-aa01-1f6c7db4a780",
    "detailedMessage": "Vertex with id already exists: "
}
 (499)
    at Connection._handleMessage (/var/task/node_modules/gremlin/lib/driver/connection.js:282:9)
    at WebSocket.<anonymous> (/var/task/node_modules/gremlin/lib/driver/connection.js:130:43)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.EventEmitter.emit (domain.js:483:12)
    at Receiver.receiverOnMessage (/var/task/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.EventEmitter.emit (domain.js:483:12)
    at Receiver.dataMessage (/var/task/node_modules/ws/lib/receiver.js:413:14)
    at /var/task/node_modules/ws/lib/receiver.js:379:23
    at /var/task/node_modules/ws/lib/permessage-deflate.js:298:9 {
  statusCode: 499,
  statusMessage: '{"code":"ConstraintViolationException","requestId":"0a0fe863-aa17-44bf-aa01-1f6c7db4a780","detailedMessage":"Vertex with id already exists: "}',
  statusAttributes: {}
}


```

**To Reproduce**

Import an account into AWS perspective

**Expected behavior**
Excepted the GremlinFunction to appear in Lambda functions of Perspective.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by thebutler12** [comment]
Hey, 

You will only see the **GremlinFunction** (which is deployed by the AWS Perspective stack) if you import the AWS Perspective deployment Region from **Account A.** Perspective will not automatically import its own resources. 

You can import **Account A** using the same process as you used to import **Account B**, but without having to deploy the AWS CloudFormation templates. You will then see AWS Perspective resources appear in your UI.

Cheers,
Matt

**Comment by siluo** [comment]
@thebutler12 thanks for your apply. Like I mentioned, the account B is the one we would like to see the diagram generated from however it does not have the GremlinFunction listed under the Lambda. And I thought GremlinFunction is the one help us to generate the diagram by following[ Build an AWS Perspective architecture diagram](https://docs.aws.amazon.com/solutions/latest/aws-perspective/web-ui-features-and-common-tasks.html#aws-perspective-architecture-diagrams) 

If I understand correctly, do you want me to import the A like what I did for B and then I should see GremlinFunction listed under B lambda?

**Comment by thebutler12** [comment]
Hi,

I am a bit lost as to what you are trying to do. 

If you have imported the Account & Region that Perspective is deployed in you will see the resources that Perspective provisions (including the GremlinFunction). We do not import this Account & Region by default as we don't want to force this upon users. 

The link you posted (https://docs.aws.amazon.com/solutions/latest/aws-perspective/web-ui-features-and-common-tasks.html#aws-perspective-architecture-diagrams) is there as an optional task to get users familiar with the UI and does require that you have imported the Perspective Account & Region

Matt

**Comment by siluo** [comment]
hey Mat,

To quote what you said above "If you have imported the Account & Region that Perspective is deployed in you will see the resources that Perspective provisions (including the GremlinFunction). " - this is something I could not see it happened in our account B which does not have the GremlinFunction. And I was able to see the error listed in the **Describe the bug** section at top, but not sure if that is the error causing us to not have the  GremlinFunction. @thebutler12

**Comment by thebutler12** [comment]
Have you imported both Account A and Account B into Perspective? You will only see the **GremlinFunction** Lambda function in the Perspective UI if you have imported the account that Perspective was deployed in (Account A).

What is your need to see the **GremlinFunction** Lambda function?

**Comment by siluo** [comment]
@thebutler12 yes, I did see GremlinFunction in account A which is the account I have AWS CloudFormation template(aws-perspective.template) launched.  

But the diagram i would like to generate to show me all the resources relations are from account B which is the one I imported after I logged to AWS Perspective from account A's AWS CloudFormation console( i used the URL on the output tab of the following format: aws-perspective-<deployment-accountID>-<deployment-region> to log to AWS Perspective). 

So I thought GremlinFunction is used to put all resources together and display them in a diagram. So I am trying to see why I cannot see GremlinFunction on account B. Please correct me if i understand incorrectly.

**Comment by thebutler12** [comment]
Thank you for clarifying. You will not see GremlinFunction in Account B as it is not deployed there. Perspective deploys a Role and some AWS Config resources in Region within Account B that you imported. There is a discovery process that runs in Account A that discovers the resources & relationships in Account B. You can just search for the resources in Account B that you want to visualize within the Perspective UI.

**Comment by siluo** [comment]
@thebutler12 so right now i have both Account A and Account B imported to AWS Perspective, so is there any way I could have all kinds of resources/services from account B displayed in one diagram?

**Comment by thebutler12** [comment]
Perspective does not have that functionality. We focused the UI on letting the user find the resources of interest via search or exploring resource types. 

We are investigating ideas for how we could offer a feature that would let you "see all resources in an account/Region". This will hopefully make it into a future release.

In the meantime, you can use the **Filters** option to only see resources from Account B within the Perspective UI.

**Comment by siluo** [comment]
Thank you. Then I will close this bug. Again, thanks for the help @thebutler12
