### ISSUE TITLE
Blank Page when adding components with filters

### ISSUE THREAD

**Issue by an-echo** [awslabs/aws-perspective#201]
**Describe the bug**
Adding elements on a view that filters TAGS (and presumably other elements) can cause an exception and result in a blank page

**To Reproduce**

1. start with a blank slate
2. Filter out tags
3. Force reload
4. search aws::rds:: and select primary instance
5. Expand on “NEPTUNE_INSTANCE_CLASS:db.r5.large” env. variable
6. Expand on the replica instance that was just added
BLANK SCREEN

**Expected behavior**
No exception

**Screenshots**
![image (13)](https://user-images.githubusercontent.com/44711656/131178574-f1b89dc4-a7ed-43fd-8609-37552845b89d.png)

**Browser (please complete the following information):**

Chrome 92.0.4515.159

**Comment by thebutler12** [comment]
Hi,

Thanks for raising this. We are investigating the issue.

Cheers,

Matt
