### ISSUE TITLE
Amazon Elasticsearch Service does not return cost data

### ISSUE THREAD

**Issue by thebutler12** [awslabs/aws-perspective#216]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
The cost data for Amazon Elasticsearch Service is missing due to the renaming to Amazon OpenSearch Service.

**To Reproduce**
1.  Open Cost Query builder
2. Select Query by Service
3. Select Amazon Elasticsearch Service
4. Submit query.

**Expected behavior**
Cost should appear for each Region Elasticsearch is deployed in.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by svozza** [comment]
Fixed in v1.1.3
