### ISSUE TITLE
Resource hover box off screen on right-hand side

### ISSUE THREAD

**Issue by tmmruk** [awslabs/aws-perspective#220]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
Hover box is off edge of screen on right hand side meaning you cannot view the Name and ARN of function. This does not happen when the popup is on the left hand side.

I have tested this to be a problem in both version 1.1.0 and 1.1.1.

**To Reproduce**

1. Log into AWS Perspective UI
2. Add any resources to diagram e.g. All Lambda Functions (under Type menu)
3. Hover over resource and see box out of screen on right hand side

**Expected behavior**
Popup box is completely visible.

**Screenshots**
<img width="761" alt="Screenshot 2021-11-15 at 15 31 55" src="https://user-images.githubusercontent.com/4531960/141809899-0f386a87-0fda-4978-b299-8cee8db5c142.png">

**Browser (please complete the following information):**

Problem is the same in Chrome 95.0.4638.69 and Firefox 91.3.0 esr

**Additional context**
Using MacBook Pro 16" (macOS Big Sur 11.6.1)
Problem is the same on external monitor (4K Dell)

**Comment by thebutler12** [comment]
Hey, thanks for raising the bug. We will look into It .

**Comment by svozza** [comment]
This was fixed in v1.1.4.
