### ISSUE TITLE
EC2 instance costs not calculated

### ISSUE THREAD

**Issue by thebutler12** [awslabs/aws-perspective#231]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
When i add EC2 instances to my diagram it shows costs as $0.

**To Reproduce**

1. Go to Perspective main screen.
2. Search for an EC2 instance
3. Select it in the dropdown
4. The diagram renders, but costs for the instance are $0

**Expected behavior**
To see the costs incurred for running these instances.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by thebutler12** [comment]
This is caused by Perspective expecting ARNs in the Cost and Usage Reports. EC2 are logged with **resourceId** inside CURs, so Perspective does not pick it up. 

You can view EC2 related costs in the Cost query builder using the **Query by Service** and selecting "Elastic Compute Cloud" and seeing the costs associated with EC2 resources

**Comment by svozza** [comment]
This was fixed in v1.1.4.
