### ISSUE TITLE
AWS perspective buckets fail security audit, getting numerous alarms

### ISSUE THREAD

**Issue by gurreriamzn** [awslabs/aws-perspective#237]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
Deployment of resources that are not secured

**To Reproduce**
Successfully deploy AWS Perspective

1. Go to arn:aws:s3:::aws-perspective-<region>-configbucket* or any bucket Perspective creates and see that Bucket policies do not enforce SSL

**Expected behavior**
Include policy to enforce SSL

**Browser (please complete the following information):**
irrelevant 
- Name chrome

**Additional context**

**Comment by svozza** [comment]
This is quite strange, the Config bucket has the https policy set as you can see here: https://github.com/awslabs/aws-perspective/blob/f1142a61c77ba4040a8a010407a84210b9116506/source/cfn/templates/zoom-import-and-aggregator.yaml#L109

Afaik, all buckets have this parameter set, e.g., 

https://github.com/awslabs/aws-perspective/blob/f1142a61c77ba4040a8a010407a84210b9116506/deployment/perspective-setup.yaml#L1169

**Comment by gurreriamzn** [comment]
Apologies, you are correct.  I checked every bucket and the policy statement is indeed there.  I've cut a ticket to the campaign team alerting them this as a false positive.
