### ISSUE TITLE
Issues with Okta - Configure AWS CloudFormation StackSets step

### ISSUE THREAD

**Issue by Klaudioz** [awslabs/aws-perspective#252]
**Describe the bug**
I can install AWS Perspective without any issue with my account. After logging into the created website, I need to make discoverable the regions, so in step 3: Configure AWS CloudFormation StackSets there are **Deploy** buttons for each region. When I click the button it opens another window where it's asking for login/password and at the same time it's kicking my opened session. I use Okta to log in, so I don't have a password.
If I go to Okta I got: "Your Amazon Web Services app password is set by your IT admin and can't be revealed."

**To Reproduce**
If you're an Okta user, after installing AWS Perspective, you'll be kicked out of your session after clicking deploy in step 3: Configure AWS CloudFormation StackSets

**Expected behavior**
Continue with the process without kicking the session out.

**Browser (please complete the following information):**

I've tried with Chrome and Firefox with the same result.

Also, I've seen the new URL opened URL in the browser is something like that:

https://us-east-1.signin.aws.amazon.com/oauth?SignatureVersion=4&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXX&X-Amz-Date=2022-02-11T16:55:45.689Z&X-Amz-Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&X-Amz-SignedHeaders=host&client_id=arn:aws:iam::1111111111111:user/cloudformation&code_challenge=XXXXXXXXXXXXXXXXXXXX&code_challenge_method=SHA-256&redirect_uri=https://console.aws.amazon.com/cloudformation/home?state=hashArgs%23stacksets%2Fcreate%3Fregion%3Deu-central-1&isauthcode=true&response_type=code&state=hashArgs#stacksets/create?region=eu-central-1

I'd like to know if there is a way to reach this URL using the UI or a way to trick it, in a way that it stops kicking out the session.

I reached AWS support and their answer was:

"This behavior is undesirable and can be disruptive to our users workflow, as you have experienced. As such I will be raising this issue with the IAM and Perspective teams as necessary in an attempt to get this issue remediated."

**Comment by thebutler12** [comment]
As a workaround, you can log into the AWS account you wish to make discoverable to Perspective using Okta in a new browser tab. Then instead of clicking the **Deploy** button in the Perspective UI. You can navigate to the CloudFormation Console in the AWS Account and Region you wish to make discoverable to Perspective and deploy the downloaded CloudFormation templates.

**Comment by Klaudioz** [comment]
Thanks for your answer @thebutler12. It allowed me to understand a little bit better the process and what I was really doing during the config process.
