### ISSUE TITLE
APIGateway Missing

### ISSUE THREAD

**Issue by khan-asif** [awslabs/aws-perspective#26]
**Describe the bug**
API Gateway data was not imported

**To Reproduce**
Regular import of primary region.

**Expected behavior**
API Gateway listed in the Resources list

**Browser (please complete the following information):**

- Name Chrome
- Version 84.0.4147.135

![image](https://user-images.githubusercontent.com/19761502/94066954-2cc45f00-fdbb-11ea-8378-ded4dd11accc.png)

**Comment by svozza** [comment]
> Regular import of primary region

By this do you mean you tried to import the account and region that AWS Perspective is installed in?

**Comment by khan-asif** [comment]
> > Regular import of primary region
> 
> By this do you mean you tried to import the account and region that AWS Perspective is installed in?

Yes, the perspective setup is in us-east-1 and the APIGateway data is not available even for us-east-1 for same account.
The listing on portal seems to be changing daily, not sure why.

Here's the list from today:

![image](https://user-images.githubusercontent.com/19761502/94156321-f84db300-fe4d-11ea-82c2-ed430a215ed7.png)

**Comment by svozza** [comment]
API Gateway resources are populated by `describe*` calls rather than AWS Config, which strikes me that there may be an issue there but given that ECS also uses the same mechanism, it's unusual that it's there and APIGW isn't. Would be happy to attach the latest logs from the ECS task so I could have a look? You may want to redact account numbers and other sensitive information before you do so.

**Comment by ConnorKirk** [comment]
Hi @khan-asif ,

We've not heard back from you in a while. I intend to close this issue.

If you are still having problems, please reopen this issue  🙂

**Comment by RWMulayAhmed** [comment]
@ConnorKirk I just completed an installation, imported an account, got the same issue. I can't see the API-Gateway either. 

![image](https://user-images.githubusercontent.com/57771133/110180266-78058380-7dd7-11eb-94f2-ef754d4cefbb.png)

Can we reopen this issue. Thanks

**Comment by svozza** [comment]
This probably means the role in the imported account has an issue. Can you find the role called `ZoomDiscoveryRole` in the account you're importing from and tell me what you see?

**Comment by RWMulayAhmed** [comment]
@svozza  I can't find a role with that name.

**Comment by RWMulayAhmed** [comment]
@svozza  it is the same case for both accounts: the one Perspective installed on and the one imported.

**Comment by svozza** [comment]
Well something has definitely gone wrong with the imported account if that the `ZoomDiscoveryRole` is not present. Were there any errors when you installed the CloudFormation you downloaded from Perspective when you imported the account? Regarding the account that Perspective is installed in, can you see a role that contains the string `PerspectiveDiscoveryRole`?

**Comment by johanbjorn** [comment]
Ok, I can't find any of my API gateways either (or ECSs for that matter). API is missing both from the account where I installed perspective and from other accounts. The ZoomDiscoveryRole is missing. What cfn template file is the ZoomDiscoveryRole supposed to be part of? a nested stack? Can we reopen?

**Comment by svozza** [comment]
When you import an account you need to install that role otherwise Perspective can't make the AWS API calls necessary to discover resources that are not supported by AWS Config.
