### ISSUE TITLE
Permission to use architecture diagram

### ISSUE THREAD

**Issue by hasanbalci** [awslabs/aws-perspective#300]
Hi, I'm currently writing my PhD thesis whose topic is about graph visualization and in my thesis I want to use the image of [architecture diagram](https://github.com/awslabs/aws-perspective/blob/main/docs/architecture-diagrams/arch-diagram.png) in the Readme of your repository. I ask for your permission to be able to use this image in my thesis. If you give permission, I will cite the url of the image unless you want me to cite another resource.

Thanks in advance!

**Comment by svozza** [comment]
You can use the image as it is covered by the Apache license we have in this repo. Best of luck on your thesis!
