### ISSUE TITLE
Discovery Process Resource Scanning Never Completes

### ISSUE THREAD

**Issue by JohnMarshall-wel** [awslabs/aws-perspective#33]
**Describe the bug**
The GUI indicates continually that the discovery resource scanning is in progress and never completes
<img width="1093" alt="Screen Shot 2020-09-25 at 6 14 16 am" src="https://user-images.githubusercontent.com/51699267/94206520-3acbca00-fef8-11ea-8965-441f5f1f801d.png">

1. Deploy the application with account
2. Access the cloud front distribution WebUI URL front end, perform first time setup options
3. Using an alternative browser context, using SAML federation / Azure AD logon authenticate to account that you wish to target for diagraming. Select configuration > Accounts and Regions, hit the import tab. Complete the account import steps and then click Deploy Template to deploy the cloud formation.
4. Ensure CF template completes successfully 
<img width="1620" alt="Screen Shot 2020-09-25 at 6 17 20 am" src="https://user-images.githubusercontent.com/51699267/94206477-1bcd3800-fef8-11ea-9955-4df13897bce4.png">

**Expected behavior**
Discovery process to complete successfully and resources available for diagraming

**Screenshots**
As per the above

**Browser (please complete the following information):**

- Name Chrome
- Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**

**Comment by svozza** [comment]
Hi John, is this the only account you've tried to import? If not how many accounts do you have scanned? For the account that appears to erroring, roughly how many resources are in the account? The reason I ask is that we've seen an issue with the payload limit in lambda for accounts that have large amounts of resources, see here #27.

**Comment by JohnMarshall-wel** [comment]
Hi @svozza , there aren't a particularly large amount of resources in the account. 

As per the below;

{
    "totalDiscoveredResources": 545,
    "resourceCounts": [
        {
            "resourceType": "AWS::Config::ResourceCompliance",
            "count": 158
        },
        {
            "resourceType": "AWS::IAM::Role",
            "count": 109
        },
        {
            "resourceType": "AWS::CloudWatch::Alarm",
            "count": 54
        },
        {
            "resourceType": "AWS::CloudFormation::Stack",
            "count": 50
        },
        {
            "resourceType": "AWS::Lambda::Function",
            "count": 40
        },
        {
            "resourceType": "AWS::EC2::SecurityGroup",
            "count": 20
        },
        {
            "resourceType": "AWS::EC2::Volume",
            "count": 17
        },
        {
            "resourceType": "AWS::EC2::NetworkInterface",
            "count": 16
        },
        {
            "resourceType": "AWS::EC2::Instance",
            "count": 13
        },
        {
            "resourceType": "AWS::IAM::Policy",
            "count": 9
        },
        {
            "resourceType": "AWS::SSM::AssociationCompliance",
            "count": 9
        },
        {
            "resourceType": "AWS::EC2::Subnet",
            "count": 9
        },
        {
            "resourceType": "AWS::SSM::ManagedInstanceInventory",
            "count": 9
        },
        {
            "resourceType": "AWS::SSM::PatchCompliance",
            "count": 8
        },
        {
            "resourceType": "AWS::KMS::Key",
            "count": 4
        },
        {
            "resourceType": "AWS::EC2::RouteTable",
            "count": 4
        },
        {
            "resourceType": "AWS::EC2::NetworkAcl",
            "count": 4
        },
        {
            "resourceType": "AWS::S3::Bucket",
            "count": 3
        },
        {
            "resourceType": "AWS::EC2::VPCEndpoint",
            "count": 2
        },
        {
            "resourceType": "AWS::SQS::Queue",
            "count": 1
        },
        {
            "resourceType": "AWS::EC2::VPC",
            "count": 1
        },
        {
            "resourceType": "AWS::S3::AccountPublicAccessBlock",
            "count": 1
        },
        {
            "resourceType": "AWS::EC2::FlowLog",
            "count": 1
        },
        {
            "resourceType": "AWS::CloudTrail::Trail",
            "count": 1
        },
        {
            "resourceType": "AWS::RDS::DBSecurityGroup",
            "count": 1
        },
        {
            "resourceType": "AWS::EC2::VPCPeeringConnection",
            "count": 1
        }
    ]

Any other ideas on what might be causing this / how to troubleshoot and diagnose. the issue?

**Comment by zainsohail88** [comment]
**bump** for this issue, we have a large number of resources in the account that I am trying to import 1000+ 
the only other account we have is the default one containing only AWS Perspective resources.

**Comment by zainsohail88** [comment]
not sure if related but this is the error I see in console
`Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.`

**Comment by svozza** [comment]
Moving the conversation here as this issue wouldn't be related to pagination, it's something going on with the the Fargate container. Can you follow the steps here and send me the logs? Please ensure to redact any sensitive information like roles or account numbers etc.

**Comment by JohnMarshall-wel** [comment]
I’m pretty sure the issue that I was having was permissions related. We didn’t have amplify enabled in the SCP but the cfn still ran successfully. When I launched the amplify console I got a deny on list apps error. I’m just organising someone to do the deployment who has a less restrictive account to confirm.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zainsohail88** [comment]
Ok thank you @svozza I went through the link and have obtained the logs, please allow us to review and redact sensitive information and I will share the logs on Monday.

in addition the Draw export option is not working in our AWS Perspective, looking deeply I found that aws-perspective-xxxxxxxxxxxx-ap-xxxxxxxxx-x-DrawIoLambdaStack-XXXXXXXXXXXX-DrawioLambdaErrorAlarm-XXXXXXXXXX is in alarm, if you want me to share logs related to it or should create a separate ticket please do let me know.

Thank You

**Comment by svozza** [comment]
Maybe create a separate issue.

**Comment by zainsohail88** [comment]
Hi @svozza as suggested I have followed the steps for [Debugging the discovery component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

1. The CloudFormation template is deployed in the region of the account I am importing and it is created successfully.
2. Double checked the account ID is correct and it is importing data (however not all of it)
3. Checking logs of Discovery Component I searched for "400" and "500" in CloudWatch I was able to get few errors which are attached with this message [log-events-viewer-result-500.txt](https://github.com/awslabs/aws-perspective/files/5365014/log-events-viewer-result-500.txt)

Also I should mention that `"totalDiscoveredResources"` on the account I am trying to import are `12645` but AWS Perspective shows `2900` resources (this number is increasing but very very slowly).

Please feel free to ask if you have any questions.

**Comment by thebutler12** [comment]
Please create a new issue tagged with v1.1.0 If you are still experiencing this issue.
