### ISSUE TITLE
Problem with import account

### ISSUE THREAD

**Issue by ccruzadogu** [awslabs/aws-perspective#36]
**Describe the bug**
When I import new account I have a problem in the cloudformation stack:

| This  policy contains invalid Json (Service: Amazon S3; Status Code: 400;  Error Code: MalformedPolicy; Request ID: 3BF5BA4C9028897C; S3 Extended  Request ID:  peGA7MR+ZNPPwH/YZ7DHihRNMuXw6hOPz0tZntARTeU9uFRp+jaV61YlAZaAcm0r4CJvL5LjPlI=;  Proxy: null)

| The following resource(s) failed to create: [ConfigBucketPolicy]. . Rollback requested by user.

**To Reproduce**
Import account in perspective account

**Expected behavior**
Complete the cloudformation without problem

![01](https://user-images.githubusercontent.com/61333482/94377402-f0f50680-00e6-11eb-97ae-f4343afb07a5.png)
![02](https://user-images.githubusercontent.com/61333482/94377403-f18d9d00-00e6-11eb-8e0c-86270afd92a2.png)
![03](https://user-images.githubusercontent.com/61333482/94377404-f2263380-00e6-11eb-87e4-d5d7d82ae1f9.png)

**Comment by svozza** [comment]
Hi there, this is a bug and we'll be releasing a fix for it in this week. You can workaround the issue as described here:

https://github.com/awslabs/aws-perspective/issues/24

**Comment by ccruzadogu** [comment]
Thanks, all is work now
