### ISSUE TITLE
Stack CREATE_FAILED

### ISSUE THREAD

**Issue by dlajwalia** [awslabs/aws-perspective#37]
**Describe the bug**
Stack creation fails. There are 4 stacks in total that fails with errors. 

**Screenshots**
To be uploaded

**Browser 
- Firefox
- Version 81.0

**Comment by dlajwalia** [comment]
![image](https://user-images.githubusercontent.com/68291266/94477450-eba7c280-019f-11eb-991f-61ba3eb3236a.png)

![image](https://user-images.githubusercontent.com/68291266/94477544-0da14500-01a0-11eb-8ed4-88d5d84488df.png)

![image](https://user-images.githubusercontent.com/68291266/94477641-2c074080-01a0-11eb-81cc-0ae52cf7f6cb.png)

![image](https://user-images.githubusercontent.com/68291266/94477713-417c6a80-01a0-11eb-9952-dff9f9a8ea14.png)

**Comment by svozza** [comment]
It looks like you've reached the limit for Elastic IP address in the region you're trying to install Perspective. You'll either need to request a service quota increase from AWS support or delete any unused Elastic IP addresses you have.

**Comment by thebutler12** [comment]
@dlajwalia did the suggestion above fix your issue? If so, i will close the issue

**Comment by dlajwalia** [comment]
No. I ensured that there were EIPs available. However, the stack still fails.

[cid:image001.jpg@01D69736.A0FE8030]

Regards,
Dhaval Ajwalia

LIXIL Water Technology Americas
Cloud Services Manager
______________________
LIXIL Link to Good Living

American Standard Brands
One Centennial Avenue
Piscataway, NJ 08854
T : 732-980-3331
Dhaval.Ajwalia@lixil.com<mailto:Dhaval.Ajwalia@lixil.com>
www.americanstandard.com<http://www.americanstandard.com/> | www.dxv.com<http://www.dxv.com/> | www.grohe.com/us<http://www.grohe.com/us>

**Comment by svozza** [comment]
For some reason the image you've posted there hasn't come through. I've just noticed in your original post that there's also a Config error there, which seems to indicate that there's already a Config delivery channel in the account (you can only have one per region).

**Comment by ConnorKirk** [comment]
Hi @dlajwalia 
We've not heard back from you in a while. I intend to close this issue. 
If we haven't solved your problem, feel free to reopen the issue
