### ISSUE TITLE
Allow filter on AWS::TAGS::TAG

### ISSUE THREAD

**Issue by stijnvanrenterghem** [awslabs/aws-perspective#40]
**Feature name**
Allow filter on AWS::TAGS::TAG

**Is your feature request related to a problem? Please describe.**
/

**Describe the feature you'd like to see implemented**
Allow to filter on AWS::TAGS::TAG

**Describe the value this feature will add to AWS Perspective**
It's nice to see the tags, but it should be hidden by default or allow a filter on tags.

**Describe alternatives you've considered**
/

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by max-allan-surevine** [comment]
Um, Either they did this really quickly or you already can. Or you need to explain what you want a bit more. I go to Filters, tick AWS::TAGS::TAG and then tags don't appear on the diagram.

**Comment by khan-asif** [comment]
> Um, Either they did this really quickly or you already can. Or you need to explain what you want a bit more. I go to Filters, tick AWS::TAGS::TAG and then tags don't appear on the diagram.

Yes it was there from Day 1.

**Comment by ConnorKirk** [comment]
Thanks for opening an issue Stijn.

It is possible to do this in the current version of Perspective. Here is a gif to show how it works
![perspective-filter-tag](https://user-images.githubusercontent.com/17845406/98100790-44e2d000-1e89-11eb-8564-a6429223d6c2.gif)

I intend to close this issue. If I can be of further help, feel free to reopen it.
