### ISSUE TITLE
Adding new account does not work as Amplify bucket is empty

### ISSUE THREAD

**Issue by Th3G4mbl3r** [awslabs/aws-perspective#44]
**Describe the bug**
I am trying to add a new account to import resources from. This is the parent account of the AWS organization and Perspective is deployed in a sub-account. However, i can neither view the template or deploy the template in the step for beginning the Cloud Formation stack deployment into accounts you want to from. This is because the amplify bucket from which these templates are supposed to be deployed is completely empty.
**To Reproduce**

1. Go to 'Account and Regions' in the left menu.
2. Click on 'Import' tab. 
3. Enter 'account number' and select 'region' for the region you want to import.
4. Click on 'Import' button.
5. Click on 'view template' button.
6. You get error message 

> <Error>
> <Code>NoSuchKey</Code>
> <Message>The specified key does not exist.</Message>
> <Key>public/cfn/import-templates/accounts/5b3674e3eb1129c175d1b591322c361ad24c856f.template</Key>
> <RequestId>77DFBD373653757A</RequestId>
> <HostId>Lhrl+tjubVkk2mqZ/iCg/+ZMxsuA5b/Nvpn1IwnDw9oBg/NKUo1ZA+lwib5xFBR0HmT7V7EpGJM=</HostId>
> </Error>

**Expected behavior**
I should be able to view the cloud formation template that needs to be deployed into my account that i am trying to add into Perspective.

**Screenshots**

**Browser (please complete the following information):**

- Name Chrome
- Version 85.0.4183.121

**Additional context**

The reason we are getting this error because even through the AWS Perspective launch cloudformation stack completed successfully, including all the sub-stacks, the amplify buckets has no contents inside. And referring to the documentation for [Automated Deployment](https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html), it does not have any additional steps to perform to populate the amplify bucket.

**Comment by thebutler12** [comment]
I believe this is related to #8. We have fixed the issue in v1.0.1. If you are happy to delete the v1.0.0 stack and redeploy using the latest from [here](https://aws.amazon.com/solutions/implementations/aws-perspective/?did=sl_card&trk=sl_card) that will fix your issue. We understand that might be quite painful and are working on instructions to be able to upgrade from v1.0.0. These will be available soon. 

As a temporary workaround, the templates are stored in the DiscoveryBucket. You can download these replace the `AccountId` and `AggregationRegion` parameters with the account Dd and Region you deployed Perspective in. Then you can deploy this in the account and Region you are importing.

**Comment by Th3G4mbl3r** [comment]
> I believe this is related to #8. We have fixed the issue in v1.0.1. If you are happy to delete the v1.0.0 stack and redeploy using the latest from [here](https://aws.amazon.com/solutions/implementations/aws-perspective/?did=sl_card&trk=sl_card) that will fix your issue. We understand that might be quite painful and are working on instructions to be able to upgrade from v1.0.0. These will be available soon.
> 
> As a temporary workaround, the templates are stored in the DiscoveryBucket. You can download these replace the `AccountId` and `AggregationRegion` parameters with the account Dd and Region you deployed Perspective in. Then you can deploy this in the account and Region you are importing.

I will undeploy and redeploy. However, in this case the [documentation link for the launch template](https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html) should also be updated constantly to refer to the correct version of the cloudformation template.

**Comment by Th3G4mbl3r** [comment]
I've read trough the issue #8 and this is not the same error. This error occurs because the amplify bucket is empty. If the step to enable "Public Access to Amplify Bucket" is a mandatory step, then we should make sure that it is documented appropriately as not being optional or provide the steps for a manual workaround if the optional step cannot be performed.

**Comment by stakahashi** [comment]
+1

**Comment by thebutler12** [comment]
Please create a new issue tagged with v1.1.0 if you are still experiencing this issue.
