### ISSUE TITLE
Discovery never completes

### ISSUE THREAD

**Issue by adnanfida** [awslabs/aws-perspective#45]
**Describe the bug**
I deployed the solution more than a week ago. Every time I try to access the CloudFront hosted UI, I get the message that "discovery process is scanning the resources in 1 region" and never gets out of this state.

**To Reproduce**
1. Deploy the solution in any account
2. Visit the CloudFront hosted UI

**Expected behavior**
I should be able to show what the UI has to offer.

**Screenshots**
![image](https://user-images.githubusercontent.com/52178390/94823647-b2eb3180-03c9-11eb-83b9-e5a6ea48e4c8.png)

**Browser (please complete the following information):**

- Chrome
- Version 85.0.4183.121

**Additional context**
None

**Comment by thebutler12** [comment]
It sounds like something has gone wrong with the discovery process. Please run through [Appendix E](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html) in the implementation guide and let us know what you find.

If you are going to post snippets of a log file, please ensure that you remove any data you don't want the world to see.

**Comment by adnanfida** [comment]
Run through [Appendix E](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html):

1. Import is for the account where the solution was deployed so no additional accounts to import and specifying the current account ID in Account & Region Manager > Import tab shows and an error that account already exists.

2. No additional account was imported so nothing else to check.

3. None of the Logs have 400 or 500 in them.

**Comment by xionghou** [comment]
I got the same issue and could not find any related logs, the discovery lambda just timeout

**Comment by svozza** [comment]
Every call times out?

**Comment by svozza** [comment]
@adnanfida I have a working theory that this might be something to do with API throttling. Can you send me the logs anyway?

**Comment by fumio-tiger** [comment]
Hi, there.

I am having the same problem and the "Discovery process is scanning resources in 1 region(s)" is showing for over an hour.

Is this a reasonable amount of time?

I followed Appendix E and checked the CloudWatch logs for Gremlin Function, but did not find any error logs.

Also, the total number of resources in AWS Config is 215.

This is the log that was output to the CloudWatch logs of Gremlin Function.

```
START RequestId: 293dc8cc-78db-4bd3-9c9d-a8e44200a54d Version: $LATEST
--
2020-12-27T19:42:45.251Z	293dc8cc-78db-4bd3-9c9d-a8e44200a54d	INFO	Executing command: { command: 'getAllResources', data: { accountFilter: {} } }
2020-12-27T19:42:45.544Z	293dc8cc-78db-4bd3-9c9d-a8e44200a54d	INFO	connected
END RequestId: 293dc8cc-78db-4bd3-9c9d-a8e44200a54d
REPORT RequestId: 293dc8cc-78db-4bd3-9c9d-a8e44200a54d	Duration: 316.99 ms	Billed Duration: 317 ms	Memory Size: 1024 MB	Max Memory Used: 109 MB	Init Duration: 635.13 ms	XRAY TraceId: 1-5fe8e3b4-1b00ad855e6b14a67369b24d	SegmentId: 75c3506f74d9cbec	Sampled: true
START RequestId: 7d70d98e-64ca-44e2-b203-a6f4c5813a02 Version: $LATEST
2020-12-27T19:42:48.776Z	7d70d98e-64ca-44e2-b203-a6f4c5813a02	INFO	Executing command: { command: 'getAllResources', data: { accountFilter: {} } }
2020-12-27T19:42:48.860Z	7d70d98e-64ca-44e2-b203-a6f4c5813a02	INFO	connected
END RequestId: 7d70d98e-64ca-44e2-b203-a6f4c5813a02
REPORT RequestId: 7d70d98e-64ca-44e2-b203-a6f4c5813a02	Duration: 97.19 ms	Billed Duration: 98 ms	Memory Size: 1024 MB	Max Memory Used: 109 MB	XRAY TraceId: 1-5fe8e3b8-795bb95915b73ca62681a9da	SegmentId: 5df7213b373b94c3	Sampled: true
```

Any ideas?

**Comment by fumio-tiger** [comment]
After about 8 hours, the message "Discovery process is scanning resources in 1 region(s)" is still displayed....
😢

**Comment by svozza** [comment]
It's very likely this issue (workaround included):

https://github.com/awslabs/aws-perspective/issues/98

**Comment by fumio-tiger** [comment]
@svozza 
thanks!!

I hadn't found that Issue, I'll be checking it!😀

**Comment by ankitosh** [comment]
https://github.com/awslabs/aws-perspective/issues/35

Facing similar issue, scanning never complete.

**Comment by thebutler12** [comment]
Please create a new issue tagged with v1.1.0 if you are still experiencing this issue.
