### ISSUE TITLE
We could not retrieve your import configuration or it has been corrupted

### ISSUE THREAD

**Issue by b52guy** [awslabs/aws-perspective#48]
Just installed the scripts and logged into the website.  This error is all I can see.
We could not retrieve your import configuration or it has been corrupted

**Comment by b52guy** [comment]
Nested stack failure.  
Failed to put delivery channel 'aws-perspective-xxxx-us-east-1-DiscoveryImport-VC3H1149G9ZD-DeliveryChannel-9C50YTE8LROD' because the maximum number of delivery channels: 1 is reached. (Service: AmazonConfig; Status Code: 400; Error Code: MaxNumberOfDeliveryChannelsExceededException; Request ID: xxcff06b-b25f-4a83-b39b-98717e92fa90; Proxy: null)

**Comment by svozza** [comment]
That normally means you're trying to deploy in an account that already has Config installed.
