### ISSUE TITLE
Within Arc diagram pricing shows 0$ 

### ISSUE THREAD

**Issue by almoayyed** [awslabs/aws-perspective#49]
**Feature name**
Add pricing for all resource, currently it display 0$ 

![image](https://user-images.githubusercontent.com/70891241/94999193-7d5c6900-05c0-11eb-9a83-1c8819981101.png)

**Comment by toksvaeth** [comment]
Hi,

The initial implementation of the costing feature requires a bit of manual effort to set up after installation.

Can you please confirm you have followed the instructions under _Set up the cost feature_ in the [Implementation Guide](https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html#step-2.-post-deployment-configuration-tasks)?

**Comment by ConnorKirk** [comment]
Hi @almoayyed,
I'm closing this issue, as we've not heard back from you. If your issue isn't solved, please reopen this issue 👍
