### ISSUE TITLE
Deleting CFN results in old S3 Buckets remaining behind in error state

### ISSUE THREAD

**Issue by Th3G4mbl3r** [awslabs/aws-perspective#50]
**Describe the bug**
I had to delete the AWS Perspectives stack. After i completed the full deletion process, the S3 console, still has a few old S3 buckets which are left in an error state. Refer to the attached diagram to see the error state buckets.

**To Reproduce**
Deploy v1.0 of the stack and then run a discovery process on your existing account. Once it completes, delete the stacks completely. If they error out, resolve the errors manually and then ensure that the stack is deleted completely from the cloudformation console.

The go to S3 console and look through the buckets.

**Expected behavior**
The buckets either should not be deleted at all or deleted completely and cleanly. It should not be left in this error state.

**Screenshots**
![image](https://user-images.githubusercontent.com/23739284/95062503-a4857880-072f-11eb-8c39-3ebad3b9227b.png)

**Browser (please complete the following information):**

- Name Chrome
- Version 85.0.4183.121

**Additional context**
None

**Comment by svozza** [comment]
Are the buckets empty?

**Comment by ConnorKirk** [comment]
Thanks for raising this issue @Th3G4mbl3r 

I believe this is the same issue as #30 
The custom resource that attempts to clean up the buckets before deletion is not working correctly. We will fix this in the upcoming release. 
I intend to close this issue and use #30 for tracking.
