### ISSUE TITLE
not load resource configuration

### ISSUE THREAD

**Issue by rsiripan** [awslabs/aws-perspective#51]
Receive this error message when at first logon -- We could not load resource configuration. Refresh the page to try again, - no resource display either

sound like we are reaching to the maximum configuration at somewhere, do you know where I can change that configuration?  The error disappear If we filter and drop to just a few aws accounts.

**Comment by svozza** [comment]
Yes, this is a known issue due to the payload limitations of of the lambda function. We will be looking to implement pagination in an upcoming release to solve this. Unfortunately the only workaround currently is what you are doing by using the account filters to reduce the size of the payload coming from the backlog.

https://github.com/awslabs/aws-perspective/issues/27

**Comment by ConnorKirk** [comment]
Thanks for opening this issue @rsiripan 
 I intend to use #27 to track this issue and close this one. If we can be of more assistance, feel free to reopen it.

**Comment by rsiripan** [comment]
Thaks for the updated & looking forward to the next release..


______________________________________________________
Ray Siripan
Senior Cloud Solution Architect
Group IT

TUI Group
Wigmore House | Wigmore Lane | Luton | UK
Phone: +44 7786 004 052
Email: Ray.Siripan@tui.com<mailto:Ray.Siripan@tui.com>

Website: http://www.tuigroup.com<http://www.tuigroup.com/>
LinkedIn: https://www.linkedin.com/company/tuigroup
Twitter: https://www.twitter.com/tuigroup

Chairman of the Supervisory Board: Dr. Dieter Zetsche | Executive Board: Friedrich Joussen (CEO), Birgit Conix, David Burling, Sebastian Ebel, Dr. Elke Eller, Frank Rosenberger | Company seat: Berlin/Hannover | Commercial register: Amtsgericht | Berlin-Charlottenburg HRB 321 | Hannover HRB 6580

[A close up of a sign  Description automatically generated]
[A close up of a sign  Description automatically generated]
[A close up of a sign  Description automatically generated]
[A close up of a sign  Description automatically generated]
[A close up of a sign  Description automatically generated]
[A picture containing drawing  Description automatically generated]
