### ISSUE TITLE
Very Slow Discovery

### ISSUE THREAD

**Issue by JorgeRenAscend** [awslabs/aws-perspective#52]
**Describe the bug**
After deploying the solution stack in my account, I added one of my regions to discover, after 5 hours running, it has only discovered 835 resources in my account. The number of resources in the account is big, maybe around 5k

**To Reproduce**

1. Deploy the solution
2. Add a region with a lot of resources to discover
3. Wait a lot of hours

**Expected behavior**
Is it intended to take so long to discover all of my resources? I only see like 2 or 3 new per minute

**Comment by svozza** [comment]
What resource types are coming back?

**Comment by JorgeRenAscend** [comment]
From the time that I created this issue tho now, the discovery has found 1233 resources
From the current results types I got

```
AutoScaling (2)
CloudFormation (9)
CloudWatch (124)
EC2 (446)
ElasticLoadBalancingV2 (7)
IAM (248)
RDS (2)
S3 (103)
TAGS (292)
```

**Comment by svozza** [comment]
Can you go to the AWS Config aggrgator and see how many and what sort of resources are in there?

**Comment by JorgeRenAscend** [comment]
AWS Config

![image](https://user-images.githubusercontent.com/58462399/95152135-929ae880-07b6-11eb-9272-e526e519aa4d.png)

**Comment by svozza** [comment]
Is this coming from the Aggregator section?
<img width="185" alt="Screenshot 2020-10-06 at 08 58 15" src="https://user-images.githubusercontent.com/8573472/95174561-261dea80-07b2-11eb-90dd-49b9aa9907c4.png">

**Comment by JorgeRenAscend** [comment]
![image](https://user-images.githubusercontent.com/58462399/95175058-1c61aa80-07e5-11eb-87cf-e54ba07fc2fe.png)

**Comment by svozza** [comment]
sorry, I wasn't clear. Is the first screenshot you sent with all the Config resources taken from when you click on `PerspectiveConfigAggregator` there?

**Comment by JorgeRenAscend** [comment]
yes

**Comment by svozza** [comment]
Sorry, I thought I'd replied to this! I have a working theory that this maybe something to do with API throttling. Could you follow the steps here to get me some logs (don't forget to redact any sensitive info like account numbers etc):

https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html

**Comment by thebutler12** [comment]
Please create a new issue tagged with v1.1.0 if you are still experiencing this issue.
