### ISSUE TITLE
Allow Parameters for Elasticsearch Instance Size (in particular t3)

### ISSUE THREAD

**Issue by codypenta** [awslabs/aws-perspective#53]
**Feature name**
Give your feature a name.

Enable selection of instance sizes for elasticsearch

**Is your feature request related to a problem? Please describe.**
A description of what the problem is.

You can choose Neptune database size based on the workload. Can we do the same for elasticsearch? Especially now that t3 are an option:

https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-elasticsearch-service-offers-t3-instances/?sc_channel=em&sc_campaign=Launch_mult_LA_awslaunchemail_20200914&sc_medium=em_whats_new&sc_content=launch_ot_ot&sc_country=mult&sc_geo=mult&sc_category=mult&sc_outcome=launch

**Describe the feature you'd like to see implemented**
A description of what you would like to see.

When I deploy the stack, I can choose elasticsearch instance size similar to neptune with a sane default.

**Describe the value this feature will add to AWS Perspective**
Tell us how this feature might improve AWS Perspective.

Allows customer to customize instance size for neptune and elasticsearch, effectively right-sizing their workload

**Comment by svozza** [comment]
Thanks for the feature request, the team were only discussing adding this yesterday so it's definitely something we want to do.

**Comment by svozza** [comment]
Implemented in #89
