### ISSUE TITLE
Formation CREATE_FAILED due to invalid policy JSON in template

### ISSUE THREAD

**Issue by navado** [awslabs/aws-perspective#58]
Attempt to provision aws-perspective into additional region failed.
[invalid.template.zip](https://github.com/awslabs/aws-perspective/files/5342070/invalid.template.zip) located here: https://aws-perspective-amplifystoragebucket-14lu9llypry0f.s3.amazonaws.com/public/cfn/import-templates/regions/e1f925c485684f555c87a2fd5b792d05ecbd2bd8.template?X-Amz-Algorithm
[valid.template.zip](https://github.com/awslabs/aws-perspective/files/5342101/valid.template.zip)
Editing template resolves the issue. See attachments for reference.

**Comment by svozza** [comment]
What version are you using? This issue should have been fix in the new release.

**Comment by navado** [comment]
How do I see it and how do I upgrade?

**Comment by svozza** [comment]
Unfortunately the only upgrade strategy currently to uninstall and reinstall. However, we are working on a script that will allow in place upgrades. If you'd like I can put a note in this issue for you when it's done, it shouldn't be too long now.

**Comment by ConnorKirk** [comment]
#86

**Comment by mohsanjaffery** [comment]
Fixed in v1.0.1
