### ISSUE TITLE
Question: Does this solution "maps" data interactions in between infrastructure services?

### ISSUE THREAD

**Issue by mllanes** [awslabs/aws-perspective#60]
Hi,
Wanted to know if this solution graphically maps interactions in between infrastructure elements, for example, "Lambda A" calls "Lambda B" or "Fargate Task A" retrieves messages from "SQS queue B"

Thanks!

**Comment by svozza** [comment]
We do map relations between services but obviously not every combination. We currently don't support that SQS use case but we do have plans to.

**Comment by mllanes** [comment]
Thank you for the quick response. The use case of "Lambda A" calling "Lambda B" does gets mapped then? Wondering how is that achieved? Are the CloudTrail Data Events captured and parsed?

**Comment by svozza** [comment]
In the case of lambda we currently parse the lambda code (only Node.js at the moment) and try to identify S3 buckets and databases that have been injected in as environment variables. It might be possible to detect lambdas that way too but it would require a code change most likely. We are just using plain `get*` and `describe*` calls to do this. We do have plans to use AWS Config events for more realtime updates.

**Comment by mllanes** [comment]
Thanks for the clarification. Closing the issue.

**Comment by svozza** [comment]
No problem, any more question don't hesitate to reach out.
