### ISSUE TITLE
boto_utils.py and decorators.py are excluded from git

### ISSUE THREAD

**Issue by adam-tylr** [awslabs/aws-perspective#64]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
I'm trying to build from source but `boto_utils.py` and `decorators.py` are not present in `source/backend/functions/lambda-layers/`. I see these directories being excluded in the `.gitignore` and an exception for those files but it doesn't work. I believe you need a `/*` after `/python`

```
source/backend/functions/lambda-layers/decorators/python/*
source/backend/functions/lambda-layers/boto_utils/python/*
```

**To Reproduce**
Clone repo. Files are missing

**Comment by svozza** [comment]
Makes sense, we'll add them back in.
