### ISSUE TITLE
We could not load resource configuration. Refresh page to try again. See GitHub issuesfor help resolving the issue

### ISSUE THREAD

**Issue by malupo** [awslabs/aws-perspective#75]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
I get this everytime I go into the Perspective.  I don't have anything defined in my region -- and I've taken the defaults when configuring AWS Perspective

**To Reproduce**
Take AWS perspective defaults.  Always comes up with this message.

1

**Screenshots**

Chrome

**Additional context**

**Comment by svozza** [comment]
Have you imported any accounts?

**Comment by malupo** [comment]
I have clicked on "import account" -- and put in my account number.  However..... I have never "exported" anything to "import"

**Comment by svozza** [comment]
I ask this because this sounds like an issue when you have lots of resources in your account as mentioned in #27 so I was wondering if that might be what's happening in your case.

**Comment by malupo** [comment]
I don't have any resources in my account. -- And I have selected my account in the import option.  I believe #27 had a different problem because he could narrow down his selection.    I have installed the perspective in mutliple accounts (both work and personal account) and have always gotten this message.   I will create an EC2 image to see if it is a problem with an empty account.

**Comment by svozza** [comment]
Can you try just importing the Perspective account? It should be the first option when you log in to Perspective for the first time. That doesn't require any CloudFormation so it should import a bunch of stuff so we can see if that's working.

**Comment by malupo** [comment]
Right now deleting stacks... Will recreate aws-perspective stacks in a region where I have a small setup... and then try importing the perspective account as you;'ve indicated.

**Comment by malupo** [comment]
Wow Cool!  I was able to see my region diagrammed nicely after 1)  waiting for all components to complete in CF and 2) specifying the account when I first logged into the CF distribution URL.  So problem solved.  I have many questions but in respect to not convoluting this issue, I will go into research mode.  Thanks.

**Comment by svozza** [comment]
Great! If you've not seen it to the `Import an account` section here in the Implementation Guide (https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html) for steps on how to import other accounts.

**Comment by malupo** [comment]
succesfully resolved.
