### ISSUE TITLE
Customization on AWS perspective UI

### ISSUE THREAD

**Issue by awsyadav** [awslabs/aws-perspective#79]
**Replacing the AWS Perspective name with Custom Name and log**

Is it possible to replace the AWS Perspective Name from the Cognito login page & From Static Page ? If yes then please suggest the code and step to do the same

Is it possible to add the Custom logo (ex- Company Logo) ? If yes then please suggest the step to do the same

**Comment by ConnorKirk** [comment]
Thanks for opening an issue

You could change the detail on the login page by customising the text in `source/frontend/src/App.js` 
Here is a link to the file
https://github.com/awslabs/aws-perspective/blob/f490977d44571f17089da64e0b6b83c380732da7/source/frontend/src/App.js#L30

You could add a custom logo in a similar manner. It depends where you wish to add the logo.  The Header component could be a potential candidate https://github.com/awslabs/aws-perspective/tree/master/source/frontend/src/components/Header

I hope this helps.

**Comment by ConnorKirk** [comment]
Hi @awsyadav ,
I've not heard back from you, so I assume you have received the help you need.
We don't intend to add further features to customise the Perspective UI at this time.

I intend to close this issue. If you require further help on this topic, feel free to reopen this issue.
