### ISSUE TITLE
Import Account/Region Error “S3 error: X-Amz-Algorithm only supports "AWS4-HMAC-SHA256" For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html”

### ISSUE THREAD

**Issue by thebutler12** [awslabs/aws-perspective#8]
**Describe the bug**
When i try and import an account or Region. I generate the template and click 'Deploy Template' but i get an error when trying to load the template in CloudFormation. It says S3 error: X-Amz-Algorithm only supports "AWS4-HMAC-SHA256" For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**To Reproduce**

1. Go to **Configuration** -> **Accounts & Regions**
2. Click on **Import**
3. Add 12-digit account id to import
4. Select a **Region** from the dropdown
5. Click **Import**
6. Click **Deploy Template**
7. Click **Next**

Error S3 error: X-Amz-Algorithm only supports "AWS4-HMAC-SHA256" For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html appears in a red bar at the top of the page.

**Expected behavior**
I should be taken to the AWS CloudFormation console and be able to deploy the template

**Screenshots**

**Additional context**

**Comment by thebutler12** [comment]
If you are seeing this issue, please ensure you have followed the **Post Deployment configuration tasks** section in the deployment guide [here](https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html#step-2.-post-deployment-configuration-tasks). Specifically the **Enable public object access on the AWS Amplify storage bucket**. This will allow AWS CloudFormation to access the import template from S3.

**Comment by an-echo** [comment]
The post deployment task can be reduced by making the bucket available to the organization instead of making the templates public object.
Sample policy 
` {
  "Version": "2012-10-17",
  "Statement": {
    "Sid": "AllowPutObject",
    "Effect": "Allow",
    "Principal": "*",
    "Action": "s3:GetObject",
    "Resource": "arn:aws:s3:::my-bucket/*",
    "Condition": {"StringEquals":
      {"aws:PrincipalOrgID":["o-xxxxxxxxxxx"]}
    }
  }
}`

**Comment by lgbaeza** [comment]
> If you are seeing this issue, please ensure you have followed the **Post Deployment configuration tasks** section in the deployment guide [here](https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html#step-2.-post-deployment-configuration-tasks). Specifically, the **Enable public object access on the AWS Amplify storage bucket**. This will allow AWS CloudFormation to access the import template from S3.

The Post-deployment configuration tasks explains that "Block all public access" should not be enabled, but it doesn't says that the bucket needs to have public write permissions. In addition, I reviewed the amplifystorage where the template GUI is trying to save the template and it doesn't have any files on it. 

When I click the "Import" button it appears to be a forbidden error
<img width="1008" alt="error perspective" src="https://user-images.githubusercontent.com/23559150/93912811-d6c3be80-fcc9-11ea-9045-374d1c19907d.png">

**Comment by khan-asif** [comment]
Primary: us-east-1;  Import worked for Oregon region with no issue.

**Comment by thebutler12** [comment]
> > If you are seeing this issue, please ensure you have followed the **Post Deployment configuration tasks** section in the deployment guide [here](https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html#step-2.-post-deployment-configuration-tasks). Specifically, the **Enable public object access on the AWS Amplify storage bucket**. This will allow AWS CloudFormation to access the import template from S3.
> 
> The Post-deployment configuration tasks explains that "Block all public access" should not be enabled, but it doesn't says that the bucket needs to have public write permissions. In addition, I reviewed the amplifystorage where the template GUI is trying to save the template and it doesn't have any files on it.
> 
> When I click the "Import" button it appears to be a forbidden error
> <img alt="error perspective" width="1008" src="https://user-images.githubusercontent.com/23559150/93912811-d6c3be80-fcc9-11ea-9045-374d1c19907d.png">

The error you are seeing in the console is that Perspective is trying to upload an object (the cfn template) with ACL of 'public-read' to the amplifystorage bucket and it is being blocked by the bucket policy.  Configuring the **amplifystorage** bucket as outlined in the **Enable public object access on the AWS Amplify storage bucket** section of the [post-deployment steps](https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html#step-2.-post-deployment-configuration-tasks) should fix this. Be aware you may have other account wide settings that block making public S3 Objects.

We are working on a method that will remove the need to make public S3 objects for CloudFormation to access, instead we will allow the cfn template to be downloaded and you will have to manually deploy using the CloudFormation console.

**Comment by Th3G4mbl3r** [comment]
> > > If you are seeing this issue, please ensure you have followed the **Post Deployment configuration tasks** section in the deployment guide [here](https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html#step-2.-post-deployment-configuration-tasks). Specifically, the **Enable public object access on the AWS Amplify storage bucket**. This will allow AWS CloudFormation to access the import template from S3.
> > 
> > 
> > The Post-deployment configuration tasks explains that "Block all public access" should not be enabled, but it doesn't says that the bucket needs to have public write permissions. In addition, I reviewed the amplifystorage where the template GUI is trying to save the template and it doesn't have any files on it.
> > When I click the "Import" button it appears to be a forbidden error
> > <img alt="error perspective" width="1008" src="https://user-images.githubusercontent.com/23559150/93912811-d6c3be80-fcc9-11ea-9045-374d1c19907d.png">
> 
> The error you are seeing in the console is that Perspective is trying to upload an object (the cfn template) with ACL of 'public-read' to the amplifystorage bucket and it is being blocked by the bucket policy. Configuring the **amplifystorage** bucket as outlined in the **Enable public object access on the AWS Amplify storage bucket** section of the [post-deployment steps](https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html#step-2.-post-deployment-configuration-tasks) should fix this. Be aware you may have other account wide settings that block making public S3 Objects.
> 
> We are working on a method that will remove the need to make public S3 objects for CloudFormation to access, instead we will allow the cfn template to be downloaded and you will have to manually deploy using the CloudFormation console.

The **Enable public object access on the AWS Amplify storage bucket** section of the [post-deployment steps](https://docs.aws.amazon.com/solutions/latest/aws-perspective/automated-deployment.html#step-2.-post-deployment-configuration-tasks) is supposed to be optional. But looks like in this case it should not be optional or the documentation should be updated to clearly document what will break in the UI if you do not perform the optional step and instead provide guidance on how to work around it manually.

**Comment by mohsanjaffery** [comment]
This is fixed in v1.0.1
