### ISSUE TITLE
Referring to issue id 79

### ISSUE THREAD

**Issue by awsyadav** [awslabs/aws-perspective#91]
Thanks for reverting,
https://github.com/awslabs/aws-perspective/issues/79

As you suggested i tried finding the App.js & Header source folder, but I could not see the same source code in any lambda or s3 bucket.

I just deployed the cloud formation template, not sure how aws source code is getting referred.

Currently, the cloud formation template is deployed and aws perspective is working, we have two requirement 

1st is to change the "Sign in to AWS Perspective" With "Welcome to Orgname AWS Inventory"

2nd Replacing "AWS Perspective" name  which appears after login to Cognito user with "Orgname AWS Inventory"

Please suggest the real-time changes for the above two requirements.

Thanks,

**Comment by ConnorKirk** [comment]
Hi @awsyadav 

Sorry, I was not clear in my instructions earlier.
The files in the S3 buckets have been minified, so you won't be able to easily amend them. It is possible, but I don't recommend it.

Instead, I suggest you clone/fork this repository. Then edit the files in `App.js` and `Header.js` in your own version of Perspective. Then, you will need to rebuild and deploy the site yourself. 

See [README - Deployment](https://github.com/awslabs/aws-perspective#deployment) for instructions about building and deploying Perspective from source.

**Comment by ConnorKirk** [comment]
Hi @awsyadav ,
I'm going to close this issue for now, as I've not heard anything further from you. I hope you managed to solve your issue.
