### ISSUE TITLE
Discovery process in scanning resources is taking too long. 

### ISSUE THREAD

**Issue by SriPrasanthG** [awslabs/aws-perspective#94]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
A description of what the bug is.

**To Reproduce**

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

I have followed the instructions step by step and was able to launch CFT successfully without an error and don't even see any error in the log. PFA.
<img width="915" alt="p1" src="https://user-images.githubusercontent.com/24395663/99961428-6d892600-2db4-11eb-87e0-e90f8c695f06.PNG">

**Comment by svozza** [comment]
Are you just trying to import the account that Perspective is installed in or is it a separate account?

**Comment by SriPrasanthG** [comment]
Hi, I imported a region for the account where I deployed the perspective.


Regards,
Prasanth

**Comment by svozza** [comment]
Is it the same region that you installed Perspective in? I ask, because if it's a different region you need to install some CloudFormation to allow config to write to the aggregator.

**Comment by SriPrasanthG** [comment]
Yeah, I did it in the same region where I installed it.

**Comment by svozza** [comment]
There are another set of logsthat might have more info, got to the console and go to `ECS -> aws-perspective-<your-account-number>-cluster -> Tasks -> Stopped` and check the logs of any of the stopped tsaks to see if there's any errors in there.

**Comment by llsilva-aws** [comment]
I got exactly the same issue as above, the pipeline was broken in the build phase because of that:
https://www.docker.com/increase-rate-limits
In my case, to resolve the issue, I have ran the build once on my local environment (Cloud9) in order to create the image in ECR. Everything worked from there. I had to wait 5-10 minutes for the ECS task to start again by itself and voila.

**Comment by svozza** [comment]
We've a workaround here now that the public ECR registry has been launched: #98.

**Comment by byongwu** [comment]
Hi. I am also having problem with this.
I tried following action items but my importing is still taking 3 hours without much progress. It's still spinning on the UI message of `Discovery process is scanning resources in 1 region(s)`.

* the fresh AWS account
* the latest AWS Perspective template
* importing the fresh AWS account that got Perspective deployed

Could any of you try the very latest AWS Perspective template with a fresh AWS account to see if you have the same error?

FYI. This is the screenshot of CloudWatch.
![image](https://user-images.githubusercontent.com/69205204/101236794-410bcd00-3717-11eb-92e5-c8c52a9f97aa.png)

I am willing to help you debug the issue. I need this new service enabled to analyze the customer's account's architecture. Please tell me which logs I should take a look at. I can even share the AWS-employee-only account I deployed. Please ping me. Thanks!

**Comment by svozza** [comment]
Have you checked whether this is the Docker issue mentioned above?

**Comment by byongwu** [comment]
@svozza . No, I haven't.
Actually, I looked at https://github.com/awslabs/aws-perspective/issues/94#issuecomment-734926695, but could not understand how to check if this is Docker issue.
@llsilva-aws , if you have some time could you elaborate what files to check and what line/text to check?

Regardless, if I am having out-of-the-box failure, shouldn't others have failures, or maybe someone in charge of this project can test it? Maybe there can be automated test report on the CloudFormation deployments? Just suggestion. It would be nice to know if there is a data showing that recent vanilla deployment worked or not worked.

I will use manual methods to analyze my customer's architecture. So I am in no hurry, but enabling this would really help.

**Comment by llsilva-aws** [comment]
Hi @byongwu, you can check the issue in the CodePipeline, more precisely in the build action. Check the logs and you will be able to see the docker error 429.

**Comment by svozza** [comment]
> @svozza . No, I haven't.
> Actually, I looked at [#94 (comment)](https://github.com/awslabs/aws-perspective/issues/94#issuecomment-734926695), but could not understand how to check if this is Docker issue.
> @llsilva-aws , if you have some time could you elaborate what files to check and what line/text to check?
> 
> Regardless, if I am having out-of-the-box failure, shouldn't others have failures, or maybe someone in charge of this project can test it? Maybe there can be automated test report on the CloudFormation deployments? Just suggestion. It would be nice to know if there is a data showing that recent vanilla deployment worked or not worked.
> 
> I will use manual methods to analyze my customer's architecture. So I am in no hurry, but enabling this would really help.

If you look in the pinned issue here (https://github.com/awslabs/aws-perspective/issues/98), there are steps on how to identify and fix the issue.

**Comment by svozza** [comment]
@byongwu, did the steps in #98 help solve your issue?

**Comment by svozza** [comment]
I am going to close this issue for now, feel free to discuss in #98 if required.
