### ISSUE TITLE
Discovery process is taking too long after the perspective implementation successfully 

### ISSUE THREAD

**Issue by SriPrasanthG** [awslabs/aws-perspective#95]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
A description of what the bug is. I have followed the instructions step by step and was able to launch CFT successfully without an error and don't even see any error in the log. PFA.

**To Reproduce**

**Expected behavior**
A description of what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/24395663/99961791-09b32d00-2db5-11eb-8e41-7c0186324fee.png)

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by mohsanjaffery** [comment]
Tracking this in https://github.com/awslabs/aws-perspective/issues/94
