### ISSUE TITLE
Docker Hub Rate Limiting Workaround

### ISSUE THREAD

**Issue by svozza** [awslabs/aws-perspective#98]
## Description

Docker Hub has recently implemented rate limiting for downloading Docker images from their website. As the Discovery process relies on the base `nodejs` image hosted there, sometimes when installing AWS Perspective and error will occur when building the container for Fargate to run.

## How Do I Know I'm Affected

Typically, listing the AWS Perspective images in ECR (it will be named `perspectivecontainerrepo-` with a random alphanumeric string appended) should display the image built during install, this will be empty if there has been an error. Alternatively, you may check the CodePipeline job to see if the build has errored (it will be named `aws-perspective-<your-account-number>-<region>-TaskStack-` with a random alphanumeric string appended).

## Remediation
It is possible that by restarting the CodePipeline job, the build may run successfully but for a more reliable workaround, changing the Discovery process Dockerfile to use a different public repository is preferred. This will require you to clone the git repository and build the container locally before pushing it to ECR. 

1. Clone the Perspective repository:
```bash
git clone git@github.com:awslabs/aws-perspective.git
```
2. Enter the AWS Perspective directory
```bash
cd aws-perspective
```
3. Enter the Discovery process code directory
```bash
cd source/backend/discovery
```
4. Replace the contents of the Discovery Docker in (`source/backend/discovery/Dockerfile`) file with the following:
```Dockerfile
FROM public.ecr.aws/bitnami/node-snapshot:12

RUN groupadd -r discovery && useradd -r -g discovery discovery

RUN npm config set unsafe-perm true

RUN mkdir /code

WORKDIR /code

COPY package.json .

RUN npm install

COPY src/ src/

CMD ["node", "src/discovery/discovery.js"]
```
5. Go to the AWS Perspective repository in ECR in you account and click `View push commands` and follow the instructions in the dialog box that appears. These commands must be ran in the same directory as the Discovery process Docker file (`source/backend/discovery/Dockerfile`).

This is will be fixed in the new `1.1.0` release and this workaround will no longer be required.

**Comment by itsgsurya** [comment]
I have seen the info "This is will be fixed in the new 1.1.0 release and this workaround will no longer be required."

how can I roll out the new version on my infrastructure? do we have step by step doc?

**Comment by byongwu** [comment]
@svozza 
In my case, I am having the problem you mentioned above. My build has failed.
I would like to dig more but I do not know where is `source/backend/discovery/Dockerfile` located in my AWS account.
Could you give me a tip on where I can find that file? I searched ECS/ECR/CodePipeline but could not find easily.

**Comment by svozza** [comment]
You need to follow this step from the workaround:

> This will require you to clone the git repository and build the container locally before pushing it to ECR.

It's not as clear as it should be so I'll update the steps.

**Comment by svozza** [comment]
> I have seen the info "This is will be fixed in the new 1.1.0 release and this workaround will no longer be required."
> 
> how can I roll out the new version on my infrastructure? do we have step by step doc?

The new release is still in the development phase, when it comes out there will be a full set of instructions on how to updgrade but essential it will just involve using the Update operation that CloudFormation provides.

**Comment by itsgsurya** [comment]
thx for the info. prepare the document from the laymen's point of view.

**Comment by svozza** [comment]
Updated now.

**Comment by itsgsurya** [comment]
Cloud you please provide product walkthrough videos as well. It is really useful for end-users. 

More awareness will give you more success !!

**Comment by fumio-tiger** [comment]
@svozza 

I read this Issue you gave me and tried the steps you wrote.
As a result, the resource shows up! Thanks!

But I'm not sure, so I have one question about the procedure.

> 5. Go to the AWS Perspective repository in ECR in you account and click View push commands and follow the instructions in the dialog box that appears. These commands must be ran in the same directory as the Discovery process Docker file (source/backend/discovery/Dockerfile).

After modifying the Dockerfile and pushing the built Docker image to the ECR, when I access the AWS Perspective URL and log in, will the pushed Docker image be used?

Sorry for the newbie question....

**Comment by svozza** [comment]
Yep, once it's pushed when the scheduled Fargate container runs the latest version from your ECR repo will be used.

**Comment by fumio-tiger** [comment]
@svozza 

Thank you so much!
I really appreciate your help!

**Comment by svozza** [comment]
Not a problem! Don't hesitate to ask any more questions too.

**Comment by svozza** [comment]
> Cloud you please provide product walkthrough videos as well. It is really useful for end-users.
> 
> More awareness will give you more success !!

I'm only seeing this now, we are actually looking into making some videos publicly available.

**Comment by smankoo** [comment]
In the workaround, can you please add instructions to add the right tag to the new image being pushed or change the tag in the task definition? Otherwise it doesn't work.

**Comment by jtgutt** [comment]
> 
> 
> In the workaround, can you please add instructions to add the right tag to the new image being pushed or change the tag in the task definition? Otherwise it doesn't work.

Yes, wish I'd had such instructions, as this is what tripped me up.  Maybe there's a better way, but I ended up fixing my tag mismatch (details in #170).
